### ISSUE TITLE
We need more examples, preferably live demos that are online

### ISSUE THREAD

**Issue by uffou** [kusti8/proton-native#100]

**Comment by parro-it** [comment]
This is a native GUI framework, how can you have "live demos that are online" ?
It cannot run in a browser...

**Comment by kusti8** [comment]
I agree with having more examples, but you can't have live demos of a native framework. Then you just end up making it in React web, which defeats the purpose.

**Comment by SkyzohKey** [comment]
Demo can be put online as GIF guys xD

**Comment by vikkio88** [comment]
@SkyzohKey he asked for "live demos", in the case of GIFs he could have phrased it as "screengrab" "animated screenshot", live demo feels a bit more like an interactive one.

I do agree thought that the Docs is a bit empty, needs some images. If you want I could open a PR making some screenshots of the various Controls API on Linux @kusti8

**Comment by kusti8** [comment]
Yeah gifs are the best that we can get. If you could make some that would
be great. I'll get along to making some more examples and gifs of that
later.

**Comment by chiedo** [comment]
Hey fellas!

I just started putting together a YouTube video series to go over some examples...

I'm planning to walk through each of the components. Just started this morning but wanted to get feedback before continuing

Does this seem like it would be helpful at all? If not, what did you have in mind?

https://www.youtube.com/playlist?list=PLhqsxkaH18naEwN_92zkwrvZXVhC7Ooq9

**Comment by vikkio88** [comment]
what OS are you using?

**Comment by chiedo** [comment]
Mac OS @vikkio88

**Comment by chiedo** [comment]
I should probably specify! Good call

**Comment by chiedo** [comment]
Ahhh thanks @vikkio88, Just habit I guess haha

**Comment by kusti8** [comment]
I've added more examples. I'll improve documentation as in #145
