### ISSUE TITLE
Tray Support

### ISSUE THREAD

**Issue by JackPyro** [kusti8/proton-native#101]
Is Tray supported or gonna be supported in future versions?

**Comment by parro-it** [comment]
Actually [libui-node](https://github.com/parro-it/libui-node) does not support them, because they are not implemented in [libui](https://github.com/andlabs/libui) (see this issue there: https://github.com/andlabs/libui/issues/216).

You can try to 👍🏻 that issue to get them implemented there.
Or alternatively, we can use other existing npm packages to implement it?
@kusti8 any thoughts?

**Comment by kusti8** [comment]
I don't think working with other node packages is going to work that well. I looked quickly and there doesn't seem to be anything cross platform and I assume all the solutions have their own blocking event loop and implementation into JSX is going to be non trivial.

**Comment by parro-it** [comment]
> I looked quickly and there doesn't seem to be anything cross platform and I assume all the solutions have their own blocking event loop and implementation into JSX is going to be non trivial.

If `libui` does not want to implement it, I could write a new package that leverage the event loop of libui-node

**Comment by kusti8** [comment]
I don't think that would be that good and it could get out of hand quickly. @JackPyro what exactly do you mean by tray? There's this https://github.com/mikaelbr/node-notifier which can send notifications. But if you want a tray icon it doesn't seem like there's anything good that works.

**Comment by mengkheang** [comment]
Would be nice if it has system tray support

**Comment by JackPyro** [comment]
@kusti8 More like this:
![image](https://user-images.githubusercontent.com/5402106/39887690-87a0ca88-549b-11e8-9da5-58558a68f293.png)

I've got my answer, so feel free to close this issue.

**Comment by Darkle** [comment]
What about using https://github.com/zaaack/node-systray?

**Comment by parro-it** [comment]
> What about using https://github.com/zaaack/node-systray?

Seems nice

**Comment by parro-it** [comment]
But there's not C++ code, neither C, how could it work?

**Comment by kusti8** [comment]
Seems like it uses https://github.com/zaaack/systray-portable which is Go
code.

**Comment by parro-it** [comment]
ah ok not it make sense

**Comment by Darkle** [comment]
https://github.com/zaaack/systray-portable seems to include precompiled binaries for each OS though.

**Comment by parro-it** [comment]
@Darkle, if you mean in libui-node:

> Actually libui-node does not support them, because they are not implemented in libui (see this issue there: andlabs/libui#216).

libui-node is and will remain only a binding library to what libui implements. But what's wrong using systray-portable directly in app code?

**Comment by kusti8** [comment]
Once you get down the road of adding random binaries to stuff like libui-node or proton native, it gets to be a mess, not just because you have to manage one more build scheme, but also because you end up bloating it with people asking why not this binary also. 

I'll make a page in the docs to address third party solutions such as this, but they should be separate.

**Comment by parro-it** [comment]
> I'll make a page in the docs to address third party solutions such as this, but they should be separate.

We should start an awesome-desktop-js list...

**Comment by Darkle** [comment]
> We should start an awesome-desktop-js list...

Here are some links I have stored in Evernote related to js and desktop app dev:

- https://github.com/BrigJS/brig
- Node exe packagers:
		- https://github.com/nexe/nexe 
		- https://github.com/pmq20/node-packer
		- http://nectarjs.com/
		- https://github.com/zeit/pkg
		- http://thecodebarbarian.com/standalone-express-apis-binaries-with-pkg.html
		- https://www.npmjs.com/package/lone
- https://github.com/parro-it/libui-node
- https://github.com/parro-it/libui-node/blob/master/docs/initialization.md
- https://github.com/nacmartin/nodetcltk
- https://github.com/trueinteractions/tint2
- https://github.com/joeferner/wxNode
- https://github.com/sindresorhus/trayballoon
- https://github.com/breach/thrust/
		- https://news.ycombinator.com/item?id=8604716
- http://quaxe.org/
- https://livecode.com
- https://github.com/HackPlan/quark-shell-mac
- https://github.com/glennw/servo-shell
- https://github.com/ocornut/imgui
- https://github.com/pojala/electrino
- https://github.com/WebReflection/jsgtk
- https://github.com/Shouqun/node-skia
- https://github.com/facebook/yoga
- http://libyue.com/docs/latest/js/guides/getting_started.html
- https://github.com/kusti8/proton-native

**Comment by khanhas** [comment]
Electron supports creating Tray menu out of the box.   
Tray as well as toast notification are basic elements of what we calls "Apps" nowadays.   
Using third-party package is fine but I think you guys should aim proton-native as a one-go solution to create a complete app.

**Comment by mischnic** [comment]
Example for node-systray with proton-native:
The only glue code needed is calling the `kill` method from node-systray.

```js
import React, { Component } from 'react';
import SysTray from 'systray';
import fs from "fs";

import { render, Window, App, Box, TextInput, Menu } from 'proton-native';

const systray = new SysTray({
    menu: {
        // you should using .png icon in macOS/Linux, but .ico format in windows
        icon: new Buffer(fs.readFileSync("/.../icon.png")).toString('base64'),
        title: "Test",
        tooltip: "Tips",
        items: [{
            title: "Item",
            tooltip: "Item Tooltip",
            enabled: true
        }, {
            title: "Exit",
            tooltip: "bb",
            enabled: true
        }]
    },
    debug: false,
    copyDir: true
})

systray.onClick(action => {
    if (action.seq_id === 0) {
      console.log("Hi!");
    } else if (action.seq_id === 1) {
      systray.kill()
    }
});

const stop = ()=>{
  systray.kill(false)
};

class Example extends Component {
  render() {
    return (
      <App onShouldQuit={stop}>
        <Menu>
          <Menu.Item type="Quit"/>
        </Menu>
        <Window onClose={stop} title="Proton Native Rocks!" size={{w: 400, h: 400}} menuBar={false}>
            <Box>
            	<TextInput>Hi</TextInput>
            </Box>
        </Window>
      </App>
    );
  }
}

render(<Example />);

```

**Comment by styfle** [comment]
@Darkle Do you mind if I make the awesome list starting with your notes?

**Comment by Darkle** [comment]
@styfle Yeah sure thing.

**Comment by parro-it** [comment]
@styfle I also have a gist where I collected link, articles and interesting snippets of code, mainly about libuv and GUI event loops https://gist.github.com/parro-it/842ff46a86142c30b1f94f97bb738418.
Really caotic, but something could be useful...

**Comment by Darkle** [comment]
@mischnic re:
https://zaaack.github.io/node-systray/classes/_index_.systray.html#kill
```
const stop = ()=>{
  systray.kill(false)
};
```

Why would you kill systray here, but not the node process?

**Comment by kusti8** [comment]
@Darkle because this is called when the window or app is closed, so the node process is already stopping, so the last thing we need to stop is the systray. The event loop gets stopped when you have a last Window left or the app quits through Menu.

**Comment by styfle** [comment]
@Darkle @parro-it I got a list started here: https://github.com/styfle/awesome-desktop-js

Feel free to send a PR 👍
