### ISSUE TITLE
Error when trying npm run start

### ISSUE THREAD

**Issue by appsdevpk** [kusti8/proton-native#104]
Attached is the output of the console. And i just installed the proton-native and everything went well except when i try to start the app i got this error.

![proton-native-error](https://user-images.githubusercontent.com/516860/39652385-c76ed0c2-5006-11e8-9576-bf309360c430.png)

**Comment by mischnic** [comment]
Somehow the dependencies weren't installed correctly. Could you please run `npm install` (maybe after deleting the `node_modules` folder).

**Comment by appsdevpk** [comment]
Here is the out put of npm install and then npm run start
![proton native error 2](https://user-images.githubusercontent.com/516860/39676125-97c4d7a8-517e-11e8-9540-faadfae4c924.png)

**Comment by mischnic** [comment]
Please the node_modules folder and then run "npm install".

**Comment by Iakow** [comment]
Hi! I have the same trouble. Removing node_modules and running "npm install" does not help.

**Comment by mischnic** [comment]
Is `windows-build-tools` installed? -> `npm install --global --production windows-build-tools`




@parro-it

**Comment by Iakow** [comment]
Yes.

**Comment by mischnic** [comment]
Could you please post a list of all files in the "myapp\node_modules\libui-node" folder?

**Comment by parro-it** [comment]
From the logs, it seems @appsdevpk is using windows 32bit. @Iakow are you running on the same platform?

If so, could you please both manually download this https://github.com/parro-it/libui/releases/download/alpha3.5-004/libui-shared-windows-ia32-alpha3.5-004.tar.gz zip, and download it in "myapp\node_modules\libui-node" folder?

**Comment by parro-it** [comment]
Is the file `myapp\node_modules\libui-node\nbind.node` present?

**Comment by parro-it** [comment]
Also, if you are using `windows-build-tools` to compile, please make sure you have [Visual C++ Redistributable Package per Visual Studio 2013](https://www.microsoft.com/it-it/download/details.aspx?id=40784) installed.

**Comment by Iakow** [comment]
Inatalling C++ 2013 installation helped.

**Comment by parro-it** [comment]
> Inatalling C++ 2013 installation helped.

We should add a note somewhere... @msink is doing a beautiful work with CI building on libui: https://github.com/andlabs/libui/pull/358, this problem will be probably solved soon by using Visual Studio 2015 to build prepublished libui binaries

**Comment by appsdevpk** [comment]
Installing C++ 2013 Redistributable package resolved the issue
