### ISSUE TITLE
onChange on initial start

### ISSUE THREAD

**Issue by mischnic** [kusti8/proton-native#108]
The onChanged event gets emitted when rendering the element for the first time (without any user interaction).

```jsx
import React, { Component } from 'react';
import { render, Window, App, Entry, Box, ColorButton } from './src';

class Example extends Component {
  render() {
    return (
      <App>
        <Window
          title="Proton Native Rocks!"
          size={{ w: 300, h: 300 }}
          menuBar={false}
        >
          <Entry onChange={a => console.log(a)}>Some Text</Entry>
        </Window>
      </App>
    );
  }
}

render(<Example />);
```

Without typing anything:
```
$ npx babel-node test.js
Some Text
```

**Comment by mischnic** [comment]
> I suspect this is due to the fact that it creates the onCreate callback

`onChange` gets fired in `DesktopComponent.initialProps`:

https://github.com/kusti8/proton-native/blob/d37dae1299527cfc51905b8eccdc1d398ebe413f/src/components/DesktopComponent.js#L200-L213

**Comment by kusti8** [comment]
Yeah so once it sets the onChange callback, it sets the children as well. So if libui fires onChange when the text property is set, then that may be it. I still have to try it out and see.

**Comment by mischnic** [comment]
It's libui-node ('s fault):

```cpp
void UiEntryBase::setText(std::string text) {
	uiEntrySetText(uiEntry(getHandle()), text.c_str());
	if (onChangedCallback != NULL) {
		(*onChangedCallback)();
	}
}
```

libui doesn't call `onChanged` with `setText`.

**Comment by kusti8** [comment]
Yeah that makes sense. It's not that big of a deal and it would be ugly to fix it in proton-native. For some applications that store the value, it may be desirable so that you get the default value, others not so much.

**Comment by parro-it** [comment]
We can remove the callback change from the setter of property if you think it can improve things.
