### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by probablyup** [kusti8/proton-native#11]
Are you planning on implementing a [Stylesheet API](https://facebook.github.io/react-native/docs/stylesheet.html) like `react-native` has? Curious how we could tie in something like [`styled-components/native`](https://www.styled-components.com/docs/basics#react-native) to enable a full visual solution.

**Comment by dariocravero** [comment]
It would also be interesting to leverage RNs primitives (like calling Box View) and use a flexbox model (perhaps through yoga) to make it super transparent to jump on it. Will try to explore those areas soon. Do you have any thoughts on that? Thanks for putting this together btw! It has tonnes of potential!

**Comment by kusti8** [comment]
I don't have any experience with yoga so I wouldn't know where to start. A stylesheet would depend on how libui will get more features. I don't know if there are enough styles to constitute a stylesheet.

**Comment by mdings** [comment]
Is there a way _at all_ currently to apply styling to the elements?

**Comment by kusti8** [comment]
Not right now no. If libui gets more features I'll add it, but for now you can just create objects with all the props and then add `{...myStyle}` to the component props.

**Comment by adamierymenko** [comment]
I'd prefer something somewhat more minimal that Qt or even React Native's style sheets. I think the use case for this library is clean, fast, small native UI apps.
