### ISSUE TITLE
Not expanding on linux?

### ISSUE THREAD

**Issue by utvk** [kusti8/proton-native#113]
Hi,

wonder if this is a bug on linux? Or misunderstanding?

With the code below I would expect both the button and the textinput to expand, when resizing the window in the horizontal direction. This is because grid children should have extend set to default value.

But it doesn't seem to stretch out the controls, the width stay the same?

````jsx
      <App>
        <Window title="Proton Naive Rocks!" size={{w: 300, h: 300}} menuBar={false}>
          <Grid padded={true}>
            <Button row={0} column={0}>
              Hello
            </Button>
            <TextInput row={0} column={2}>
              Hi
            </TextInput>
          </Grid>
        </Window>
      </App>
````

**Comment by SkyzohKey** [comment]
A screenshot is always appreciated when reporting UU glitches...

**Comment by kusti8** [comment]
Grid is very weird with how it works. Try changing the align properties to only have it align one way and then try again.

**Comment by utvk** [comment]
Yea, it's a bit strange. Worked as expected when align set to {h: false, v: true} Thanks @kusti8  !

So to recap (with some added screenshots now, sorry):

````jsx
        <Window title="Proton Naive Rocks!" size={{w: 600, h: 300}} menuBar={false}>
          <Grid padded={true}>
            <Button row={0} column={0} align={{h: false, v: true}}>
              Hi
            </Button>
            <TextInput row={0} column={2} align={{h: false, v: true}}>
              World
            </TextInput>
          </Grid>
        </Window>
````
Works fine and controlled are stretched.

![ok](https://user-images.githubusercontent.com/6271182/39710279-a6306e44-521c-11e8-8ed2-aed0c08472d5.jpg)

When I removed the align properties, the controls doesn't stretch.

![notok](https://user-images.githubusercontent.com/6271182/39710312-c28735a0-521c-11e8-8d27-abd25b1f87a3.jpg)

Not sure if this is a bug or not, but maybe should be mentioned in the docs as it's a little confusing as I was thinking the expand property should handle this.
