### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by bdunn313** [kusti8/proton-native#118]
Problem: This is a great package and people like me want to contribute while fitting into the current flow of the existing contributors.

Solution: `CONTRIBUTING.md` or some other approach to providing a guide (however brief) into what is expected for an effective contribution. 🎉

**Comment by Migweld** [comment]
This is a fine idea. I've canvassed some examples for perusal:

[Node](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md)
[Gutenberg](https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md)

**Comment by kusti8** [comment]
I've pushed a quick write up of a contribution guide, which I'll add to over time.
