### ISSUE TITLE
"Node doesn't like ES6" (terminology)

### ISSUE THREAD

**Issue by BillyWM** [kusti8/proton-native#12]
This is not true as of Node 6, where 99% of ES6 is supported with only 3 particular subfeatures missing (and Babel doesn't transpile them all for you, such as tail-call optimization).

Here's a chart: http://node.green

You may be thinking of other features that developers commonly use, like async/await or object rest/spread, but these are not part of "ES6" (ES2015) but rather later yearly standards revisions (ES2016 - ES 2018)

Many of these features are indeed supported in the most recent stable + LTS releases of Node (8 and 9) -  the ones offered by default for download on the Node site

**Comment by kusti8** [comment]
Ok, I think I just had an old version of node on my computer, so that's why. I'll fix it now.
