### ISSUE TITLE
TypeScript type declaration 

### ISSUE THREAD

**Issue by khanhas** [kusti8/proton-native#122]
I have recently just pulled request new definition files for our package on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25705). If this goes through, TypeScript user will be able to install `@types/proton-native` package and start making app with TypeScript easier and faster.

I covered almost  all Components , but it still has some problems and I need your help:
- [x] Passing props for children.
    - [Grid](https://proton-native.js.org/#/component_APIs/grid_components)'s `row`, `column` or [Form](https://proton-native.js.org/#/component_APIs/form)'s `label` are props that are only available for components inside them. They shouldn't available for components outside of `<Grid></Grid>`, `<Form></Form>`. I don't know how to achieve that.
- [x] Universal props
   - Although currently, there's only one universal prop but how it is defined halt me from adding it in. Are all universal props from now on always excluded from Tabs, Grid children, Combobox/RadioButton Items, MenuBar? Or each one of them will have a separate list of exclusion? Depends on that, I choose a fast approach to `extends` props list for all components.

If you like TypeScript and Proton-native and want to contribute, please do comment it here or my pull request on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25705) or pull a request on [my fork](https://github.com/khanhas/DefinitelyTyped). 
Any help would be greatly appreciated!  
Happy coding!

**Comment by kusti8** [comment]
Looks nice. I haven't done TypeScript at all, so I wouldn't really be of much use. So as for your first point, I don't know what's available or what can be done. For your second point, universal props aren't a set list with set exclusions. They're a list of props that most items implement.

**Comment by khanhas** [comment]
Thank you very much! I will include universal prop soon.
I create this Issue for more like a discussion thread than an actual issue. So can you add some label for this thread to gain some attention from user/dev that are familiar with using React/React Native + TypeScript?

**Comment by kusti8** [comment]
Hey @khanhas what's the status on this?

**Comment by khanhas** [comment]
New update waiting for approval: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25936  

**Changes:**
- Added Grid children, label, stretchy props
Since I haven't figured it out how to pass props for children, I let all components have Grid children and `label` props. `stretchy` added where needed. This solution ensure that it won't raise any error on these props.  
Although so, I'm still not quite happy with it. Because we have to sacrifice "strictness" of type of certain components, like `stretchy` still can be applied in grid children and Grid children props can be used in every components even they're not inside a `Grid` . 
On the bright side, we are able to outsource children component in another class and still have its proper  additional props.

- Specified children type for some components.
- `Slider`: added `max`, `min` props
- `ColorButton`: `onClick` to `onChange`
- Removed undocumented components.
I just realized they are just components for bigger wrapper components, not "new, 
cutting edge" components waiting to be finished and released. User can't use them anyway so their definition are better be removed.

**Comment by khanhas** [comment]
@parro-it If you don't want to unnecessarily include Typescript and its dependencies, I think it's best to pull "Add type` request on DefinitelyTyped and let them do the job.

**Comment by parro-it** [comment]
I don't know exactly, I never used typescript, as I said, @sandangel is doing the work...
Anyway, the typescript dependency is actually added as a dev dependency, which I don't care.

**Comment by khanhas** [comment]
Area.Text are already added in @types/proton-native and waiting for approval.
Tracks its progress here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26406
Changes:
- Added AreaTextProps and AreaText component

If you want to play with Area.Text right now, manually replace this [`index.d.ts`](https://github.com/khanhas/DefinitelyTyped/blob/5d209bbbcede0582a157ee4a26b09af671409bfc/types/proton-native/index.d.ts) with the one in `./node_modules/@types/proton-native/`.   
Reload your editor.

**Comment by kusti8** [comment]
Thanks for the work on this!
