### ISSUE TITLE
Question: Plans for supporting Menu apps

### ISSUE THREAD

**Issue by alfonsodev** [kusti8/proton-native#123]
Are they plans to support these OS menus, for proton-native apps ? 
https://developer.apple.com/macos/human-interface-guidelines/extensions/menu-bar-extras/
and
https://developer.apple.com/macos/human-interface-guidelines/menus/dock-menus/

**Comment by kusti8** [comment]
This isn't on the roadmap. Proton Native uses libui, which I doubt will add support for this sometime in the future.

**Comment by mischnic** [comment]
The first feature is discussed in #101.

The second exists also on Windows ("jumplists"), but is quite a niche feature.

![no-jump-lists-for-google-chrome-on-taskbar-1](https://user-images.githubusercontent.com/4586894/39957258-51985004-55f0-11e8-96e8-5c80c1566119.png)
