### ISSUE TITLE
Menu and Menu items not showing up on Mac OS.

### ISSUE THREAD

**Issue by soorajvnair** [kusti8/proton-native#13]
Hey there, Wohoo! Finally an alternative to electron, great job! I ran the example code and the note editor showed up just fine. However the menu is missing. See the attached screenshot.

![Menu items missing](https://user-images.githubusercontent.com/4268932/36345455-d34ca2e4-1450-11e8-94be-4bd8560372da.png)

My OS is Mac OS High Sierra 10.13.3

**Comment by jrylan** [comment]
Experiencing this as well on macOS 10.13.4 Beta.

**Comment by magicpriest** [comment]
Same issue with OS X 10.13 (17A365).

**Comment by kusti8** [comment]
Seems like it's a bug in libui/libui-node. I'll look at it, but I may not have that much time.

**Comment by magicpriest** [comment]
@kusti8 
Yeah sure, this bug related to libui-node. 
I suppose its related to Sierra error which mentioned [here](https://github.com/parro-it/libui-node/issues/50), somehow core library examples cannot be run in main thread. I'll debug further on weekend, but already fall in love with your work! Thank you!

**Comment by parro-it** [comment]
Hi, [libui-node](https://github.com/parro-it/libui-node) author here.
I wrote some comment on the issue you mention.
Antway, I think the menu problerm is unrelated to that, but could depend on this issue of libui: https://github.com/andlabs/libui/issues/152

**Comment by parro-it** [comment]
See also https://github.com/parro-it/libui-node/issues/52

**Comment by andlabs** [comment]
Are you using a version of libui that has a call to `[realNSApp() finishLaunching];` in `darwin/main.m`'s `uiMainSteps()`? If not, that's the likely issue.

**Comment by parro-it** [comment]
It's using the last version of my [libui fork](https://github.com/parro-it/libui/releases/tag/pre11.alpha.4)

**Comment by parro-it** [comment]
But it doesn't seem to have any such call: https://github.com/parro-it/libui/blob/f9f91a80dd8de3a2d678383dc3468bdc424eb8ad/darwin/main.m#L162

**Comment by soorajvnair** [comment]
Thanks for taking time out to look into this @parro-it, @andlabs .

**Comment by magicpriest** [comment]
@parro-it 
Thank you for explanation.

**Comment by kusti8** [comment]
Should be fixed in the latest version.

**Comment by soorajvnair** [comment]
Awesome. Thanks for the update @kusti8
