### ISSUE TITLE
Missing features in Area

### ISSUE THREAD

**Issue by mischnic** [kusti8/proton-native#130]
- [x] scrolling area
- [x] Gradients
- [ ] Clipping
- [x] getting the Area's size in pixel (added in #174)
- [ ] make a handle to move and resize the window (`UiArea.beginWindowMove` & `UiArea.beginWindowResize`)

**Comment by mischnic** [comment]
> getting the Area's size in pixel

@kusti8 How can this be done from a API design perspective? There is no `draw` callback in declarative React code. The only way I can think of is "function as children" ("render callback"):

```jsx
<Area>
  {(width, height) => <Area.Rectangle ... > .... </Area.Rectangle>}
</Area>
```
Is that information even needed or is it enough to have `width="100%"`?

**Comment by mischnic** [comment]
And regarding gradients: how should they be declared?
1.
```jsx
const g1 = new Area.Gradient("linear", x1, y1, x2, y2); // start & end coordinates
g1.addStop(0.0, "red");
g1.addStop(1.0, "blue");

// ...

  <Area.Rectangle ... fill={g1}/>
```

2.
```jsx
const g1 = (
<Area.Gradient x1="0" x2="0" x2="100" y2="100">
  <Area.Gradient.Stop color="red" offset="0%"/>
  <Area.Gradient.Stop color="blue" offset="100%"/>
</Area.Gradient>);

// ...

  <Area.Rectangle ... fill={g1}/>
```

**Comment by kusti8** [comment]
Yeah sorry about the delay. The second option is more like the React syntax. And as for the area size, I agree that a function child is the only real way.

**Comment by mischnic** [comment]
> And as for the area size, I agree that a function child is the only real way.

I'm struggling getting that to work.
First, there is always this warning:
```
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in AREAGROUP (created by Area)
    in AREA (created by Area)
    in Area (created by Example)
    in VERTICALBOX (created by Box)
    in Box (created by Example)
    in WINDOW (created by Example)
    in APP (created by Example)
    in Example
```

The function gets passed to Area.Group as a child:

```jsx
Area.Group = class AreaGroup extends AreaComponent {
  constructor(root, props) {
    super(root, props);
    this.children = [];
  }

  appendChild(child) {
    this.children.push(child);
  }

  draw(area, p, props) {
    if(typeof this.props.children === "function"){
      this.appendChild(this.props.children(p.getAreaWidth(), p.getAreaHeight()));
    }
      
    for (let i = 0; i < this.children.length; i += 1) {
      if (typeof this.children[i] === 'object') {
        console.log(this.children[i]);
        this.children[i].render(this, area, p, props);
      }
    }
  }
};
```
This is printed to the console (returned by React.createElement via the function child):
```js
{ '$$typeof': Symbol(react.element),
  type: 'AREATEXT',
  key: null,
  ref: null,
  props: { children: '560 460' },
  _owner: null,
  _store: {} }
```
But I need something like (the real class) this for the rendering:
```js
AreaText {
  root: Root { children: [ [App] ] },
  props:
   { children:
      'Some text',
     x: 0,
     y: 0 },
  element: {},
  children:
   [ 'Some Text' ],
  str: AttributedString {} }
```

**Comment by mischnic** [comment]
> But I need something like (the real class instance) this for the rendering:

In other words: How can I invoke the reconciliation "manually" without `render`ing these elements (usually you just return them in a `render` function and the reconciler continues down)? If that's not easily possible the whole Area code would have to be restructured (probably using Context).

**Comment by kusti8** [comment]
I'm actually not sure. Could you upload your code and test so I can try it out? There may be some functions in the reconciler that can help out, like `DesktopRenderer.updateContainer(element, node, null);` (from render/index.js), but I'm not sure.

**Comment by mischnic** [comment]
```diff
diff --git a/examples/area-size.js b/examples/area-size.js
new file mode 100644
index 0000000..fb07aa5
--- /dev/null
+++ b/examples/area-size.js
@@ -0,0 +1,22 @@
+import React, { Component } from 'react';
+import { render, Window, App, Box, Menu, Area } from '../src/';
+
+class Example extends Component {
+  render() {
+    return (
+      <App>
+        <Window title="Test" size={{ w: 600, h: 500 }} margined={true}>
+          <Box padded>
+            <Area>
+              {(width, height) => (
+                <Area.Text>{`${width} ${height}`}</Area.Text>
+              )}
+            </Area>
+          </Box>
+        </Window>
+      </App>
+    );
+  }
+}
+
+render(<Example />);
diff --git a/src/components/Area.js b/src/components/Area.js
index fcc911e..73855d0 100644
--- a/src/components/Area.js
+++ b/src/components/Area.js
@@ -577,9 +577,33 @@ Area.Group = class AreaGroup extends AreaComponent {
   }
 
   draw(area, p, props) {
-    for (let i = 0; i < this.children.length; i += 1) {
-      if (typeof this.children[i] === 'object') {
-        this.children[i].render(this, area, p, props);
+    if (typeof this.props.children === 'function') {
+      /*
+        OUTPUT:
+        
+        Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
+            in AREAGROUP (created by Area)
+            in AREA (created by Area)
+            in Area (created by Example)
+            in VERTICALBOX (created by Box)
+            in Box (created by Example)
+            in WINDOW (created by Example)
+            in APP (created by Example)
+            in Example
+        { '$$typeof': Symbol(react.element),
+          type: 'AREATEXT',
+          key: null,
+          ref: null,
+          props: { children: '560 460' },
+          _owner: null,
+          _store: {} }
+      */
+      console.log(this.props.children(p.getAreaWidth(), p.getAreaHeight()));
+    } else {
+      for (let i = 0; i < this.children.length; i += 1) {
+        if (typeof this.children[i] === 'object') {
+          this.children[i].render(this, area, p, props);
+        }
       }
     }
   }

```

**Comment by maciek134** [comment]
Why not use [Refs](https://reactjs.org/docs/refs-and-the-dom.html)? Just allow the pixel size to be queried using `getWidth/getHeight`, then you can do 
```
  constructor(props) {
    super(props);
    this.area = React.createRef();
  }
  
  render() {
    return <Area ref={this.area}>
      <Area.Text>{this.area.current.getWidth()}px</Area.Text>
    </Area>;
  }
```
I'm actually working on something like that for a code editor I'm making, I'll make a PR when it works.

**Comment by maciek134** [comment]
@mischnic also about the gradients. I think the first option is more in line with how it's done in React / RN, for example with [Stylesheets](https://facebook.github.io/react-native/docs/stylesheet):
```js
const styles = StyleSheet.create({
  container: {
    borderRadius: 4,
    borderWidth: 0.5,
    borderColor: '#d6d7da',
  },
  title: {
    fontSize: 19,
    fontWeight: 'bold',
  },
  activeTitle: {
    color: 'red',
  },
});
```
```js
<View style={styles.container}>
  <Text style={[styles.title, this.props.isActive && styles.activeTitle]} />
</View>
```

**Comment by mischnic** [comment]
> also about the gradients

These are already implemented in my PR, so I'm quite reluctant to redo them.

> I think the first option is more in line with how it's done in React / RN, for example with Stylesheets:

There is nothing like that in "vanilla" React and React Native uses it because it has to serialize everything to json before sending it to the native code side. Creating explicit stylesheets enables them to use a single number to refer to all styles in that stylesheet. We don't need to do that.

> Plus it's not a good idea to carry around the overhead of React nodes when all you want is the gradient object.

No React nodes are created, this only creates elements:
```js
{  type: AreaGradient
  key: null,
  ref: null,
  props: { type: "linear", children: [/*same for children*/] },
  _owner: null,
  _store: {} }
```

**Comment by maciek134** [comment]
> No React nodes are created, this only creates elements

My mistake, I didn't look at the code. Still, that's quite a lot of overhead and it's unnecessarily complex. We are writing Javascript, not XML ;p

Simple comparison:
```js
const gradient = <Area.Gradient x1="0" x2="0" x2="100" y2="100">
  <Area.Gradient.Stop color="red" offset="0%"/>
  <Area.Gradient.Stop color="blue" offset="100%"/>
</Area.Gradient>;
```
vs
```js
const gradient = Gradient.create('linear', 0, 0, 100, 100, {
  0.0: 'red',
  1.0: 'blue',
});
```

**Comment by mischnic** [comment]
> Still, that's quite a lot of overhead

Transforming JSX to React.createElement is done by babel.
React.createElement does basically this (without ref and key handling):
```js
React.createElement = function(type, props, children) {
	return {
		type,
		props: [...props, children]
	}
}
```
The code for parsing would essentially be the same as this suggestion
```js
const gradient = Gradient.create({
  type: 'linear',
  x1, y1,
  x2, y2,
  stops: {
    0.0: 'red',
    1.0: 'blue',
  },
});
```
The only argument would correspond to `props` and `stops` would be `props.children`.

> We are writing Javascript, not XML.

XML -> HTML -> JSX
Do use React like this ? 
```jsx
import {render, App, Window, Area} from 'proton-native';
import React from 'react';

class MyApp extends React.Component {
	render() {
		return React.createElement(App, null,
			React.createElement(Window, {size: {w: 500, h: 200}, margined: true, title: 'Test'},
				React.createElement(Area, null, [
					React.createElement(Area.Circle, {x: 20, y: 40, r: 10}, null)
				]))
			)
		);
	}
}

render(React.createElement(MyApp, null, null));
```

**Comment by mischnic** [comment]
> every draw call

Thats a good point. But it can be easily solved using memoization using a WeakMap. (With a gradient based on e.g. the mouse position, your solution would suffer from the same problem.)

The question is, which API is better (ignoring the underlying implementation)? @kusti8

**Comment by maciek134** [comment]
No, because with my approach you can access `libui.DrawBrush` directly and just change what's needed. Still only one object per gradient. Memoizing mouse position based gradients would eat the RAM faster than Chrome.

**Comment by mischnic** [comment]
> No, because with my approach you can access libui.DrawBrush directly and just change what's needed. Still only one object per gradient.

How low level do you want to go? You could ditch the whole state concept and just set the text of a label using `myLabel.text = "...";`.

**Comment by maciek134** [comment]
It's not low level, if I wanted low level I'd just export the `libui.DrawBrush` constructor and be done with it. Your approach is complex for the sake of being complex and has so much drawbacks I'm surprised you went with it. @kusti8 I think you'll have to make a decision here 😜

**Comment by kusti8** [comment]
It's a tough decision. I'm leaning towards the JSX approach simply because if we end up making something like a stylesheet, that could lead to it ending up being cluttered, so that we have 3-5 StyleSheet type objects. With react, gradients end up being in the stylesheet, and I would be fine with it if we ended up making a Stylesheet and adding it there, but I don't really like creating a separate clone of it.

**Comment by maciek134** [comment]
Please consider the underlying implementation when making this decision. The JSX one is complex, resource-heavy and confusing - nowhere in the React ecosystem you define things with JSX, it's only used for rendering components.

If you knew nothing about this library and looked at the gradient code, wouldn't you think that it's a component of some kind?

I think the question we should ask when deciding whether to use JSX for something is:
> Is this code normally written inside of the `render()` method, or outside of it?

**Comment by mischnic** [comment]
>If you knew nothing about this library and looked at the gradient code, wouldn't you think that it's a component of some kind?

>Is this code normally written inside of the render() method, or outside of it?

Thats a good point...

> so that we have 3-5 StyleSheet type objects

I don't see anything upcoming in libui that would need a stylesheet.

**Comment by maciek134** [comment]
Yup, `proton-native` shouldn't need stylesheets at all.

**Comment by kusti8** [comment]
Sorry about the delay.

That's a good point. Libui won't be getting stylesheets, was thinking a bit in the future about that.

@maciek134 I like your second syntax here, although it is hard to understand what each number is from a first glance. I'm thinking a more CSS like thing where it accepts an object, so `{x1: 0, y1: 0 ...}`, but it may not be needed if its documented.

```
const gradient1 = Gradient.createLinear(0, 0, 100, 100, {
  0.0: 'blue',
  1.0: 'red',
});
const gradient2 = Gradient.createRadial(0, 0, 100, {
  0.0: 'red',
  1.0: 'orange',
});
```

**Comment by maciek134** [comment]
Well, that's how it's done in JS' Canvas: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createLinearGradient
```
CanvasGradient ctx.createLinearGradient(x0, y0, x1, y1);
```
And let's be honest, even `vim` has code completion/hints/IntelliSense today, no need to be overly expressive with the parameters.

**Comment by mischnic** [comment]
> And let's be honest, even vim has code completion/hints/IntelliSense today, no need to be overly expressive with the parameters.

How should that completion know about that proton-native function? You would need something like typescript definitions.

**Comment by maciek134** [comment]
No, not really. Most of the autocompletion solutions easily parse JS libraries, but it doesn't matter in this case since there are TS definitions for proton-native already: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/proton-native/index.d.ts

**Comment by kusti8** [comment]
If it's already used with JS canvas then it would make sense to do it that way. I'm still not a fan of the entire approach, I just like more verbose functions than less, but if it's standard then it's fine.

**Comment by kusti8** [comment]
Yeah it's long, but if it matches web JS then I prefer that over simplifying it.

**Comment by mischnic** [comment]
Fine, but I don't think many know the function signature of `createRadialGradient(x1,y1,r1,x2,y2,r2)`.

**Comment by kusti8** [comment]
Even if they don't know it and however much I don't like it myself, it is already established and I'd rather have something that mirrors what is established rather than something new. I would have made proton-native a new target for react-native instead of with a new reconciler, but a lot of features like flexbox View weren't available.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
