### ISSUE TITLE
Adding an image on the window?

### ISSUE THREAD

**Issue by Losses** [kusti8/proton-native#134]
I'm trying to add an image on the window, but there's nothing provided on the document, how can I do this?

**Comment by mischnic** [comment]
https://github.com/andlabs/libui/issues/318 needs to be resolved first.

**Comment by gregbenner** [comment]
https://github.com/andlabs/libui/blob/master/darwin/image.m this doesn't work I guess?

**Comment by Losses** [comment]
@mischnic libui supports images now :smile:

**Comment by manashathparia** [comment]
Any progress here?

**Comment by mischnic** [comment]
@manashathparia
`uiImage` was added together with tables to libui (integration into libui-node is WIP). But the actual image control didn't see any progress recently.

**Comment by jhon-andrew** [comment]
Is there a way now to render image in the window?

**Comment by gregbenner** [comment]
Think no...

**Comment by velosodigital** [comment]
Any news on this?

**Comment by Losses** [comment]
@velosodigital no

**Comment by kusti8** [comment]
V2 includes an image component and that should be released soon.

**Comment by robertveloso** [comment]
So there are plans to release the fix in next version, there's a date on it?

**Comment by kusti8** [comment]
No current dates. I need to finish up documentation for it and do a last check, but I'm a bit swamped right now with other stuff. Within the next month most likely.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
