### ISSUE TITLE
ColorButton: color format

### ISSUE THREAD

**Issue by mischnic** [kusti8/proton-native#135]
At first the onChanged events's color object returns the component values from 0-255 (but the preview on the button itself is always white - are you setting the color of underlying uiColorButton using 0-255?).  Moving the silder below the color wheel makes the button emit colors from 0-1 (the preview works but the area expected 0-255). 

![colorbutton](https://user-images.githubusercontent.com/4586894/40167533-9441d766-59c1-11e8-8fd7-84e747d8a5f4.gif)

Same code as in the previous issue:

```js
import React, { Component } from 'react';
import { render, App, Window, Area, Box, ColorButton } from './src';

class Main extends Component {
  state = {
    c: 'red',
  };

  render() {
    return (
      <App>
        <Window title="Title" size={{ w: 400, h: 400 }} margined>
          <Box padded>
            <ColorButton
              color="red"
              onChange={({ r, g, b, a }) => {
                console.log(r, g, b, a);
                this.setState({
                  c: `rgba(${r.toFixed(0)}, ${g.toFixed(0)}, ${b.toFixed(0)}, ${a})`,
                });
              }}
            />
            <Area>
              <Area.Rectangle
                x="0"
                y="0"
                width="100%"
                height="100%"
                fill={this.state.c}
              />
            </Area>
          </Box>
        </Window>
      </App>
    );
  }
}

render(<Main />);

```

Not an issue with libui-node:

```js
const libui = require('../..');

const win = new libui.UiWindow('UiColorButton example', 320, 60, true);

const widget = new libui.UiColorButton();
widget.color = new libui.Color(0, 1, 1, 1);
widget.onChanged(() => {
	console.log(widget.color)
});
win.setChild(widget);

win.show();
libui.Ui.main();
```

**Comment by mischnic** [comment]
Ok, I found the issue. What should the color format be? 0-255 or 0-1?

**Comment by khanhas** [comment]
I also want to report a problem with ColorButton.
Init `color` option is converted all wrong, both in hex and rgb format.

Example code:

```jsx
<ColorButton color="rgb(255,80,80)" />
```

And in color picker:

![image](https://user-images.githubusercontent.com/26436809/40242249-4ceba17c-5ae7-11e8-9021-7d30a9ab28be.png)

You can see R, G, B 0-255 range value are mistakenly set in 0-1 range boxes.

@mischnic, I wonder if your commit fixes this problem?

**Comment by mischnic** [comment]
@khanhas It does.
