### ISSUE TITLE
Code examples in documentation

### ISSUE THREAD

**Issue by faraazahmad** [kusti8/proton-native#145]
It would be nice to have code examples in the documentation for the props, as sometimes it can be hard to tell how to use a component and its props (especially for beginners)

**Comment by mischnic** [comment]
So you mean:

```jsx
          <RadioButtons selected={1} onSelect={v => console.log(`option no. ${v} got selected`)}>
            <RadioButtons.Item>Option 1</RadioButtons.Item>
            <RadioButtons.Item>Option 2</RadioButtons.Item>
          </RadioButtons>
```

instead of

```jsx
          <RadioButtons>
            <RadioButtons.Item>Option 1</RadioButtons.Item>
            <RadioButtons.Item>Option 2</RadioButtons.Item>
          </RadioButtons>
```

**Comment by faraazahmad** [comment]
Yeah something like that. Also, I was thinking to show separate examples for each prop.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
