### ISSUE TITLE
Suggestion for Box-based workaround for Grid limitations on macOS?

### ISSUE THREAD

**Issue by armarti** [kusti8/proton-native#147]
Hello,

First, this package is very neat.

My specs:
- macOS High Sierra 10.13.4
- proton-native@1.1.5

After reading #55  I realize I'm not the only one who can't get `Grid` to work correctly on macOS. In particular I can't get elements to be adjacent to one another.

The app UI I'm building is very easy, sketched out below (how do I make the image smaller??), and as you see I need the "Zipfile path" area to be ~2x wide as the adjacent "Select zipfile" area. I'm trying to force `Box` to do it but it seems it can only split areas symmetrically.

Any suggestions how I can make a non-symmetric vertical split in some area-type component without using `Grid`?

![sketch](https://user-images.githubusercontent.com/13367887/40630398-559e158a-62ca-11e8-9adb-56912603733b.png)

**Comment by kusti8** [comment]
It you set the select on the left hand side to not stretchy and then set the right one to stretchy it might work. I'm almost done with yoga support so when that comes out, flexbox would be supported which would make this simple.

**Comment by SomeGuy54321** [comment]
Thanks @kusti8 for the tip. I've gotten distracted with something new but I'll try this out soon.

**Comment by kusti8** [comment]
Closing for now until flexbox comes
