### ISSUE TITLE
Set state causing segmentation fault 11

### ISSUE THREAD

**Issue by n8jadams** [kusti8/proton-native#152]
This is such an intriguing library with a ton of potential! I must be doing something wrong, because I cannot accomplish a very simple task. (I am running on MacOS)

Using the following code:

```
import React from 'react';

import {
  render,
  App,
  Window,
  Box,
  Text,
  Button,
} from 'proton-native';

class Main extends React.Component {
  constructor() {
    super();
    this.state = {
      showMessage: false
    }
  }

  render() {
    return (
      <App>
        <Window title="Hello World" size={{w: 500, h: 500}}>
          <Box>
            {this.state.showMessage && (
              <Text>Hello World</Text>
            )}
            <Button
              onClick={() => this.setState({showMessage: !this.state.showMessage})}
            >
              Toggle the message
            </Button>
          </Box>
        </Window>
      </App>
    );
  }
}

render(<Main />);
```

It renders the app, but then when I click the button I get `Segmentation fault: 11`.
Why is this? I can run the `charts.js` example code just fine...

**Comment by mischnic** [comment]
Can reproduce on macOS. It seems like rendering with `this.state.showMessage = true` doesn't actually render the Text if it isn't the initial render. Then with `false`, there is no text to delete and it crashes (stack trace contains `uiBoxDelete`).

**Comment by n8jadams** [comment]
If I wrap the ternary in a `<Box>` component, it works as expected.

```
<Box>
  {this.state.showMessage && (
    <Text>Show this message</Text>
  )}
</Box>
```

This is resolved enough for me.

**Comment by mischnic** [comment]
>  I must be doing something wrong

You aren't.
Could you reopen this, please?

It also works correctly if the button is placed above the conditional text.
