### ISSUE TITLE
Can someone create Example Demo Project for Windows, macOS and Linux Desktop as target builds?

### ISSUE THREAD

**Issue by ALIENQuake** [kusti8/proton-native#156]
Hi,

I have simple project created using Windows Forms and exactly the same project created in WPF.

Can someone create Example Demo Project for Windows, macOS and Linux Desktop as target builds?

All I need is a starting point which will produce simple cross-platform GUI app. So I could just compile 3 projects and get MyApp.exe for Windows, MyApp.app for macOS and app.so for linux. Possible?

**Comment by kusti8** [comment]
JS isn't a compiled language, it's interpreted. `create-proton-app` gives you a starter template which you can work from. To make self contained executables you can follow the packaging guide, which currently doesn't support exes.
