### ISSUE TITLE
Picker onSelect returns index, not value

### ISSUE THREAD

**Issue by n8jadams** [kusti8/proton-native#158]
Here is my code that I used to test out the `Picker` component:

```
import React, { Component } from 'react';
import {
  render,
  Window,
  App,
  Box,
  Picker
} from 'proton-native';

class Main extends Component {
  handleOnSelect = selectedIndex => {
    console.log(selectedIndex);
  }

  render() {
    return (
      <App>
        <Window
          title="Testing Pickers"
          size={{w: 500, h: 300}}
        >
          <Box>
            <Picker onSelect={this.handleOnSelect}>
              <Picker.Item>Option 1</Picker.Item>
              <Picker.Item>Option 2</Picker.Item>
              <Picker.Item>Option 3</Picker.Item>
            </Picker>
          </Box>
        </Window>
      </App>
    );
  }
}

render(<Main />);
```

Is it possible to extract the text from the selected `Picker.Item`? In this example "Option 1, 2, etc...".

I can only get the index... which is useful, but I also wanted the value at the selected index.

I tried adding another argument to the `setMessage` function and that was always `undefined`.
I also tried making a `ref` for the Picker... but got confused as to how to navigate the `ref` and virtualDOM...

If there is a solution to this, it would be great to add to the docs!

Out of all the JS libraries for desktop apps, this is my favorite, even though it's still just getting started. :) Thanks!

**Comment by mischnic** [comment]
> I also tried making a ref for the Picker... but got confused as to how to navigate the ref and virtualDOM...

There is no such thing as a DOM for the native UI.

> If there is a solution to this, it would be great to add to the docs!

Yes, the docs should refer to the "(selection) index" rather than the "selection".


<br>
And this should be "number" instead of "bool":

https://github.com/kusti8/proton-native/blob/a938308d1424da503582ea7818ef6379a9b6b259/docs/component_APIs/picker.md#L63-L69

**Comment by khanhas** [comment]
@mischnic And `text` type should be `string`
