### ISSUE TITLE
about window，how to control the position , hide, display, get focus

### ISSUE THREAD

**Issue by chuanhaisoft** [kusti8/proton-native#160]
about window，how to control the position , hide, display, get focus

**Comment by mischnic** [comment]
Nothing of that is supported.

**Comment by kusti8** [comment]
Proton Native depends on libui, which doesn't have support for any of those.

**Comment by chuanhaisoft** [comment]
but these features are important

**Comment by mischnic** [comment]
Yes, they are. Proton-native is built on libui-node which is in turn a wrapper around [libui](https://github.com/andlabs/libui). These features would have to be implemented in libui itself.

Window focussing is tracked in this issue (`uiWindowRequestAttention`): https://github.com/andlabs/libui/issues/309
Window position can't be easily implement cross platform: https://github.com/andlabs/libui/issues/351

**Comment by chuanhaisoft** [comment]
If only on windows and macos?

**Comment by kusti8** [comment]
The entire point of Proton Native is that it is cross platform. Once you start making stuff that only works on one platform, it gets very confusing and defeats the purpose. This all depends on how libui implements this and when they do.
