### ISSUE TITLE
Not able to add Child Element to a Window Element - npm run start throwing error.

### ISSUE THREAD

**Issue by joshi-ankur** [kusti8/proton-native#162]
@parro-it , @mischnic , @kusti8 

So i just started working on building a proton-native desktop app on Windows 10 Pro edition.

I started off with the official documentation and  my boiler plate code was ready.

npm run start was working fine and i was able to see . Below is the attached image.
<img width="960" alt="my-desktop-app-boiler-plate-working" src="https://user-images.githubusercontent.com/36259745/41810879-2f22d680-7723-11e8-84db-9b5ee16c610e.png">

Now when i add a Box Component inside my Window component and try running the `npm run start` command, it fails :( . Have attached the image below for the same.

<img width="960" alt="my-desktop-app-boiler-plate-not-working" src="https://user-images.githubusercontent.com/36259745/41810891-675aa88e-7723-11e8-93a3-17500252711f.png">

Kindly help, i really need this to get working, am i doing something wrong?

**Comment by mischnic** [comment]
The Button needs to have the `onClick` prop (not onClicked)

**Comment by joshi-ankur** [comment]
@mischnic thanks for that change, i updated it. But then it is not solving my problem, i am still getting the same error mentioned above.

Kindly advice.

**Comment by mischnic** [comment]
> But then it is not solving my problem, i am still getting the same error mentioned above.

It's a different error (the line before the colored lines):
```
Window and Group only take one child!
```
Not sure why though.

**Comment by joshi-ankur** [comment]
@mischnic @kusti8  @parro-it  Can u please help me with a workaround to solve my problem? I need to get this desktop app up and running for my client.

**Comment by joshi-ankur** [comment]
@mischnic  yes it is a different error. 

> Window and Group only take one child

**Comment by JVisona** [comment]
@joshi-ankur try to delete the "{  }" at the line 7

**Comment by parro-it** [comment]
@joshi-ankur could you post the source code as text?

**Comment by maciek134** [comment]
@joshi-ankur  If you still need help with that, a good practice is to provide the source code for a minimal app that would reproduce this bug, nobody will retype everything from the images (in which the code is cropped btw so we can't even see some of it).

**Comment by Oxymoron290** [comment]
I was getting the error `Window and Group only take one child!` because I had a comment inside the `Window` tag...

Removing the comment inside of the window tag resolved my problem

**Comment by Oxymoron290** [comment]
![plotter](https://user-images.githubusercontent.com/2234419/59782836-72bf7880-9284-11e9-8de8-bcdaca18ab3b.gif)

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
