### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by kusti8** [kusti8/proton-native#165]
As Proton Native grows, automated tests are needed for it to work smoothly. There are a lot of edge cases that should be tested.

Currently it seems like the only way is with Xvfb, which is pretty complicated to handle with. Ideally there would be a way to test only the logic, like making a fake libui-node without GUI or something like that, or possibly on the proton-native side. I need to research and brainstorm more.

**Comment by mischnic** [comment]
> Currently it seems like the only way is with Xvfb, which is pretty complicated to handle with. Ideally there would be a way to test only the logic, like making a fake libui-node without GUI or something like that, or possibly on the proton-native side. I need to research and brainstorm more.

= Creating a wrapper around libui-node and recording all library calls.
For libui-node we will soon be comparing a screenshot from Xvfb to reference screenshots (see [here](https://github.com/parro-it/libui-napi/tree/master/tests/_snapshots/reference/darwin)).

**Comment by kusti8** [comment]
Yeah that's sort of what I was thinking. Comparing screenshots wouldn't work as well for proton native cause most of it is state stuff and logic stuff, not display.

**Comment by kusti8** [comment]
Yeah that's what I was looking at. I tried Jest and using its automatic mocking feature, but it crashes for some reason. Something to do with not liking C++ I think. So I was working on a mocked implementation. That implementation above is pretty barebones.

There's also the possibility of not mocking, but spying on selection functions. You would have to define it differently beforehand for each test depending on what you're testing, and also need Xvfb. I learning towards mocking everything, but it's going to get annoying.

**Comment by mischnic** [comment]
The classes of the [libui-node NAPI port](https://github.com/parro-it/libui-napi) (probably going to be released as version 0.4.0 - should be 100% backwards-compatible) are defined in javascript as opposed to C++. That might work better with automatic mocking?
Example: https://github.com/parro-it/libui-napi/blob/master/js/combobox.js

**Comment by mimecorg** [comment]
I agree that mocking everything manually is not a great solution, but from my experience so far it's much less work than writing the actual unit tests, so it's not that annoying. I didn't spend too much time trying to automate this.

I'm only creating a constructor for each class that I need and some empty methods, just enough so that the tests can run without any errors. I'm also using a sinon spy when I want to test if a method is called correctly. The only exception is appending/removing children from a container, where the mock methods manipulate a real array of children which can be easily compared with the expected result.

**Comment by kusti8** [comment]
The NAPI port works fine. My main concern about manually mocking isn't about the initial work putting into it, but the continued maintenance, which I don't really want to deal with. This has less room for errors.
```
import React, { Component } from 'react';
import { render, App, Window } from '../src/';
import libui from 'libui-napi';
jest.mock('libui-napi')

describe('Window and loop', () => {
  afterEach(() => {
    jest.resetAllMocks();
  });
  test('All defaults', () => {
    class Test extends Component {
      render() {
        return (
          <App>
            <Window />
          </App>
        );
      }
    }
    render(<Test />);
    expect(libui.startLoop).toHaveBeenCalled();
    expect(libui.UiWindow).toHaveBeenCalledWith('', 500, 500, true);
  });
});
```

**Comment by maciek134** [comment]
You could use docker with X.org like Selenium does and not have to worry about Xvfb. Could you elaborate on "spying on selector functions"? Because my only idea was to use [GTK Inspector](https://wiki.gnome.org/Projects/GTK+/Inspector) and its logs to do assertions.

**Comment by maciek134** [comment]
GTK Inspector is not for screenshot/reftests, it attaches to the app and can read the widget structure, styles, etc.

**Comment by maciek134** [comment]
Oh, you meant using spyOn, I was confused about the "selector functions". I'll repeat that GTK Inspector is not a screenshot tool, but you are right, there is no need to test GTK at all.

Is this something you want to do or can I do it?

**Comment by parro-it** [comment]
> Is a switch to libui-napi a thing you want?

libui-napi is a reimplementation of libui-node that uses the new N-API node libraries.
It's code will completely replace libui-node when we'll  publish next release. No need to switch.

**Comment by kusti8** [comment]
I decided to just mock all of libui, so I published [tests](https://github.com/kusti8/proton-native/tree/tests) and added some tests for Window, which seem to work.
