### ISSUE TITLE
Feature: Scrollbar

### ISSUE THREAD

**Issue by Cedware** [kusti8/proton-native#167]
Hi,
I think a Scrollbar would be a very usefull feature, especially if we need to display a long text.
A thought about something like this:
```
<Box scroll="vertical">
	<StyledText>
		{this.someLongText}
	</StyledText>
</Box>

```

**Comment by mischnic** [comment]
A scrollable *box* isn't possible, that would need to be implemented in the underlying libui library: https://github.com/andlabs/libui/issues/178.

A scrollable *area* however is implemented in libui, but not yet in proton-native: #130. If it were, you could something along the lines of:
```jsx
<Area scrolling width="100" height="100">
	<Area.Text>
		{this.someLongText}
	</Area.Text>
</Area>

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
