### ISSUE TITLE
Opening a website/webview

### ISSUE THREAD

**Issue by colinramsay** [kusti8/proton-native#169]
I'd like to launch a website either in a new window or inside my app to allow my users to go through an OAuth flow. Is this possible?

**Comment by mischnic** [comment]
Issue for webviews: https://github.com/andlabs/libui/issues/315
Issue for buttons (or similar) that open a link: https://github.com/andlabs/libui/issues/363
Issue for a link inside a text: https://github.com/andlabs/libui/issues/303

**Comment by kusti8** [comment]
[Opn](https://github.com/sindresorhus/opn) is very good, and will open a browser window. I used that in the CatApi example. Just have that run as a callback from a button press or something like that.

**Comment by gregbenner** [comment]
Is it possible now? https://doc.qt.io/qt-5/qtwebview-index.html
