### ISSUE TITLE
[Question]: USB or Bluetooth

### ISSUE THREAD

**Issue by internetstyle** [kusti8/proton-native#170]
Is Proton native able to work with USB or Bluetooth? I work with web development, but now I need to make an app that communicates with a device via USB or Bluetooth and I would like to know if Proton Native is recommended for this. Thank you.

**Comment by kusti8** [comment]
What are you trying to do? Proton native is only the GUI library, meaning that it only displays what you want it to. Anything that happens on the back end with communicating with something else is separate. You need to search for node packages to communicate. 

Personally, I would use something like mqtt for communication and skip USB.

**Comment by internetstyle** [comment]
Got it. Thank you. I believe that with node packages I can then do it. I had not understood that Proton Native was just UI. Better yet, because I'm used to React.

MQTT currently I believe that it would not be possible as it is a third party equipment, which I need to monitor via the web. Would using MQTT require hardware changes?

**Comment by kusti8** [comment]
It entirely depends on how the equipment and your idea of the stack is setup. 

What I'm thinking is you have some sort of computer like a raspberry pi interface with the equipment. That can run a web server that has a rest API that you make. Then write the web/desktop clients to interface with that. But it entirely depends on your situation and I recommend researching more generally the ideal workflow.

**Comment by internetstyle** [comment]
Thank you very much.
