### ISSUE TITLE
Area.Text does not update

### ISSUE THREAD

**Issue by grimmen** [kusti8/proton-native#171]
In the sample below, when the button is clicked only the first text line changes in the UI.  The Area.Text component keeps displaying the initial value.

```js
import React, { Component } from 'react';
import {render, Window, App, Box, Button, Area, Text,} from 'proton-native';

class Example extends Component {
  state = { flag: false };

  flagText() {
    return "Flag is "+(this.state.flag ? "Set" : "Not Set")
  }

  render() {
    return (
      <App>
        <Window title="Test" size={{ w: 600, h: 250 }} >
          <Box padded>
            <Text>{this.flagText()}</Text>
            <Area>
              <Area.Text>{this.flagText()}</Area.Text>
            </Area>
            <Button onClick={() =>
                this.setState({
                  flag: !this.state.flag,
                })
              }>Toggle Flag</Button>
          </Box>
        </Window>
      </App>
    );
  }
}

render(<Example />);
```

**Comment by mischnic** [comment]
@kusti8 The problem seems to be that the AreaText class implements only `appendChild`, so `this.children` doesn't update?

**Comment by mischnic** [comment]
I fixed a crash regarding conditional rendering in an AreaGroup along the
way, but `removeChild` is never getting called in AreaText (though
`appendChild` is). I can only pick up the change in
`AreaText.update(oldProps, newProps) `.

Gustav Hansen <notifications@github.com> schrieb am Di., 28. Aug. 2018,
16:22:

**Comment by kusti8** [comment]
That makes sense. If any props are being changed (including children), then update is being called. If we're actually adding or removing children, then removeChild is called. Sorry about that.

So we would have to create an update function. I haven't played with Area as much, but it looks like we just use deleteString and then append the new string?
