### ISSUE TITLE
Unable to Debug

### ISSUE THREAD

**Issue by AnthoniG** [kusti8/proton-native#173]
Hi,

New to this Proton Native and enjoying it :grin: 
However I am struggling to get debugging working.
I've followed the docs at :-
[Debug](urhttps://proton-native.js.org/#/debuggingl)

However nothing is working :crying_cat_face: 
I've tried installed react-devtools both globally and locally.
I've also tried installing the react-devtools-core locally and globally, but still nothing.

The react-devtools window sits there waiting and I am not sure what's going on.

Is there an example with this working ?

**Comment by AnthoniG** [comment]
Me being stupid. Guess needs more coffee lol

**Comment by awesomepeng** [comment]
> 需要更

Waiting for React to connect… how to resolve
