### ISSUE TITLE
Contents of built app

### ISSUE THREAD

**Issue by NicoAiko** [kusti8/proton-native#181]
Hey there, I have a question regarding the contents after building.
As electron-builder is used I was asking myself if there was Chromium involved.
I built an example application (the notepad one) and it's a surprising 52,1 MB big...

Could you explain why that program is so big?

I would really appreciate your answer :) thanks!

**Comment by parro-it** [comment]
No, no chromium involved... but you still get the node runtime, libui and libui-node native libraries, plus any npm dependencies you're using.

**Comment by NicoAiko** [comment]
Thanks for your answer! I'll still monitor it though. It's really big, almost no difference to electron apps. (as far as filesize is concerned)

**Comment by mischnic** [comment]
Are you using Linux oder macOS?

**Comment by NicoAiko** [comment]
I'm using macOS.

**Comment by mischnic** [comment]
The node binary is 40mb, the node_modules needed at runtime 16mb (of that 4.4 mb for the libui-node binary). Not much we can do....

**Comment by parro-it** [comment]
Not that it mean so much, but next release of libui-node will be significantly smaller

**Comment by kusti8** [comment]
Not really much to change there. Node is always going to be around that size unless we compile it ourselves, which would be a lot more work currently.
