### ISSUE TITLE
Imported Project Not Found

### ISSUE THREAD

**Issue by scottymcraig** [kusti8/proton-native#183]
After installing windows build tools and create-proton-app, receiving error "...\node_modules\libui-node\build\nbind.vcxproj(21,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk."

**Comment by mischnic** [comment]
Does running `npm install --global --production windows-build-tools` help?
Does the path to your project contain spaces?

**Comment by ateshuseyin** [comment]
windows-build-tools have some issues. See #179

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
