### ISSUE TITLE
directAccess to libUI

### ISSUE THREAD

**Issue by mfreeman-xtivia** [kusti8/proton-native#184]
Is it possible to access/use libUI components directly for which there is not (yet) a proton component?

In particular thinking it would be nice to use the Table widget from libUI

**Comment by mischnic** [comment]
proton-native relies on libui-node, which provides an interface for libui (a C library) to Javascript. For this feature to be implemented in proton-native, it first needs to be supported by libui-node (specifically, the tables are being worked on there).

**Comment by kusti8** [comment]
Due to how proton works (especially during updates of the tree which basically wipes what changed and adds another) even if such a function was present in libui-node, it wouldn't work in proton.
