### ISSUE TITLE
Stretchy does not work for StyledText

### ISSUE THREAD

**Issue by zlfnhmd** [kusti8/proton-native#185]
```
<Box padded>
    <StyledText stretchy={false} style={{ fontSize: 16 }}>
        This is some styled text.
    </StyledText>
    <Text stretchy={false}>
        This is some normal text.
    </Text>
</Box>
```
Styled text occupies the whole empty space even though stretchy is false.

**Comment by mischnic** [comment]
No, it doesn't. (Should be added to the docs though: https://proton-native.js.org/#/component_APIs/universal_props).

I *think* this is because `StyledText` creates an area internally and areas are always stretchy.

**Comment by zlfnhmd** [comment]
Can it be fixed to allow the stretchy prop?

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
