### ISSUE TITLE
Call Area.onSizeChange on initial render

### ISSUE THREAD

**Issue by mischnic** [kusti8/proton-native#186]
There is currently no way to know the area size on the initial render. So using the width/height for drawing only works after resizing.

**Comment by mischnic** [comment]
`area.js` looks like this for me before resizing the window (which sets the height). Maybe it works on Linux/Windows?
![bildschirmfoto 2018-12-27 um 19 44 58](https://user-images.githubusercontent.com/4586894/50490920-e8eacd00-0a0f-11e9-8e9d-1948a707a43d.png)

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
