### ISSUE TITLE
The linker version '2.23' used by the base 'core' is incompatible

### ISSUE THREAD

**Issue by consciousnessdev** [kusti8/proton-native#187]
I Had Error when running npm run dist
it show 

`The linker version '2.23' used by the base 'core' is incompatible with files in this snap:
    /home/abfs87/Workspace/ProtonNative/proton-app/dist/__snap-x64/prime/lib/x86_64-linux-gnu/libbsd.so.0.8.7 (2.25)
    /home/abfs87/Workspace/ProtonNative/proton-app/dist/__snap-x64/prime/lib/x86_64-linux-gnu/libexpat.so.1.6.7 (2.25)
    /home/abfs87/Workspace/ProtonNative/proton-app/dist/__snap-x64/prime/usr/lib/x86_64-linux-gnu/libexpatw.so.1.6.7 (2.25)
    /home/abfs87/Workspace/ProtonNative/proton-app/dist/__snap-x64/prime/usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10 (2.25)
    /home/abfs87/Workspace/ProtonNative/proton-app/dist/__snap-x64/prime/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0 (2.26)
  ⨯ exit status 2`

**Comment by kusti8** [comment]
This is an electron-builder problem, so I suggest you make an issue here: https://github.com/electron-userland/electron-builder

Thanks
