### ISSUE TITLE
Verify code integrity 

### ISSUE THREAD

**Issue by kontrollanten** [kusti8/proton-native#188]
Really interesting project! I'm thinking about the security issues when using JS in desktop applications. A hacker who gets access to a computer with an proton native (or electron) app installed, can manipulate the source code without the users knowledge. NW.js has solved it with [snapshots](https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot) and electron has chosen to not solve it (for now).

Would it be a solution to generate a file content hash during the build process? This hash will then be published together with the assets (like electron publishes app-update.yml) and each time the proton native application starts (with an internet connection) it'll check the hash to validate that the source code hasn't been manipulated. The hash verification will be done in a binary file.

It is not bullet proof, but it will at least add an extra security layer and may be a good starting point. To make it even more secure it may be possible to isolate the internet connection within the proton native application until the hash has been validated.

As I understand the application doesn't build any binaries today. But I think it'd be pretty simple to write a binary that acts as a wrapper to handle this; the binary verifies the hashes and then starts the application.

**Comment by manashathparia** [comment]
asar will be also ok as it is a read-only archive, so no one can modify the archive without unpacking. But sadly proton native have no support for it, but it can be ported from electron!

**Comment by kontrollanten** [comment]
> asar will be also ok as it is a read-only archive,

How do you mean with "read-only"? It's possible to just edit the content of the asar file and the application will change behaviour. Like this example https://www.howtogeek.com/368976/how-to-install-the-unofficial-dark-mode-for-slack/

**Comment by manashathparia** [comment]
> Like this example https://www.howtogeek.com/368976/how-to-install-the-unofficial-dark-mode-for-slack/

see the path they mentioned "resources/app.asar.unpacked/src/static/" its not "app.asar", its "app.asar.unpacked" means it is unpacked. and by read-only i mean you cannot change files without unpacking the asar file

**Comment by mischnic** [comment]
>  and by read-only i mean you cannot change files without unpacking the asar file

(You can just unpack it, change it and repack it.)

First of all, asar won't help at all:

>**To mitigate issues around long path names on Windows, slightly speed up require** and conceal your source code from **cursory inspection**, you can choose to package your app into an asar archive with little changes to your source code.
(https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md)

As for the first suggestion, adding a wrapper could be done without any changes to proton itself. If it's native code, adding it proton would make building significantly more complex. 

At least on macOS, it's possible to sign an application regardless of it's architecture, same for AppImage (though a costly certificate is required). That doesn't seem possible on Windows.

It's really hard to make your application secure: your potential hacker could just replace the wrapper that verifies the hashes. Or it could download malware and run it, no need for infecting a proton app directly.

> To make it even more secure it may be possible to isolate the internet connection within the proton native application until the hash has been validated.

Just don't start the app itself until the hashes have been verified.

**Comment by manashathparia** [comment]
> (You can just unpack it, modify some file and repack it.)
Yeah it is right but still, it involves doing some extra steps than just editing the js file

**Comment by kontrollanten** [comment]
> Which would mean that there is a server who is always aware whenever the user starts an application.

If the process is to just download a txt file from GitHub (or similar provider), then I can't see that it's a problem?

> It's really hard to make your application secure: your potential hacker could just replace the wrapper that verifies the hashes. Or it could download malware and run it, no need for infecting a proton app directly.

> At that point you've already lost, though. Nothing hinders the cracker at this point from swapping out the executable completely, or changing the PATH to override system defaults etc..

Sure, but then the hacker needs to rewrite the whole application to trick the user that it's the real application, right? If it's possible to add a security layer in a binary file (which can be code signed?), then it's at least a bit harder?

I'm not a security expert though, so I don't know where it's relevant to put the effort. It just feels unsafe that it is so easy to manipulate the application code.

**Comment by kusti8** [comment]
Download a hash from online leaves a lot more issues, the biggest being that it always need to be online, similar to DRM.

If an attacker already has administrative access to be able to change the files, then they could do anything that they want. The same thing is with other non compiled languages, such as Python. I'm pretty sure electron builder allows you to sign your applications if you want that.

**Comment by mischnic** [comment]
The only real solution that is more or less secure is "os-level" code signing. On macOS, this will cost you 100$/year. For Windows even more (at least 150$). electron-builder supports that on macOS and Windows.

**Comment by kontrollanten** [comment]
An idea the came to me, the hash validation should be possible to do from the compiled file, so no network connection is needed?

> If an attacker already has administrative access to be able to change the files, then they could do anything that they want.

Yes, but it's harder.

> The only real solution that is more or less secure is "os-level" code signing. On macOS, this will cost you 100$/year. For Windows even more (at least 150$). electron-builder supports that on macOS and Windows.

Code signing won't help if you change the content of the asar files?

I've changed my Slack application in seconds without repackaging and I can run it as normal. I may be missing something? If we could have a process where we have code signed binaries who validates the hash of the non-compiled files, wouldn't that make it a lot harder for an attacker? Or do you mean it isn't worth the effort?

Yes, it costs money to buy code signing certificates, but then at least the developers/users of Proton Native has an option to make it safer. I'm that there's a lot of people who think it's worth it.

**Comment by RobertZenz** [comment]
> If the process is to just download a txt file from GitHub (or similar provider), then I can't see that it's a problem?

If the machine is under control of an attacker, can you still trust network traffic?

 > Sure, but then the hacker needs to rewrite the whole application to trick the user that it's the real application, right? If it's possible to add a security layer in a binary file (which can be code signed?), then it's at least a bit harder?

No, not really. Replacing parts of the file or the whole file doesn't matter at that point anymore. The best you can do is similar to jar signing. The whole jar is being signed (with all files in it) and if one file changes, Java refuses to execute the jar. That still leaves a lot of possibilitie, for example removing the whole signing from the jar (which will make it start as unsigned jar) or sign it yourself (which will make it seemed signed, but under a different name (so not "Awesome Company Ltd." but "Avvesome Company Ltd.")).

If the cracker has write-access to the machine, you've lost. Fullstop. You can't stop the attacker at the point anymore. You can only make sure that the user has the ability to detect the attack, for example by the jar signing mechanism above. But nothing hinders the attacker from spoofing any of that.

Even if you have a full application signed, with a starter that checks that signing, there still isn't a guarantee that the file wasn't modified earlier (as stated above). Or, worse, the starter has been modified.

So I say again, if the attacker has gained write-access to the machine, it's over. Just over. At that point you can't even trust things you see on the screen anymore. What you can do is make sure that the application *arrives* at the user machine without having been tampered with.

**Comment by Lerry22** [comment]
Are you sick and tired of your cheating partner? then you need to contact these hackers AT WEBROOTHACKER@GMAIL.COM and be happy again because these set of hackers will deliver to your satisfaction, they offer various kinds of HACKING services i promise you that you will thank me later after contacting them because they are the best contact them AT = WEBROOTHACKER@GMAIL.COM
