### ISSUE TITLE
Implement <View /> with facebook/yoga flexbox

### ISSUE THREAD

**Issue by albinekb** [kusti8/proton-native#19]
Hi, nice project. I'm thinking it would be great to use https://facebook.github.io/yoga/ to create <View /> with the same support for flexbox as React Native, thoughts?

**Comment by kusti8** [comment]
Interesting, but I don't know how well that would work with libui-node. It currently implements its own type of view, with limited features. There isn't a way to set a component position. I don't have the time to add this.

**Comment by albinekb** [comment]
Yeah, I later saw that this is using libui bindings for node, I thought it was using its own renderer 👍 Maybe you should add to the readme that it is libui based?
