### ISSUE TITLE
Waiting for React to connect…

### ISSUE THREAD

**Issue by awesomepeng** [kusti8/proton-native#190]
> 需要更

Waiting for React to connect… how to resolve

_Originally posted by @awesomepeng in https://github.com/kusti8/proton-native/issues/173#issuecomment-450145089_

**Comment by mischnic** [comment]
Did you take a look at https://proton-native.js.org/#/debugging ?

You need to have `react-devtools` or `react-devtools-core` installed as a dependency **of your project**.
