### ISSUE TITLE
componentWillUnmount is not called

### ISSUE THREAD

**Issue by unlight** [kusti8/proton-native#191]
I just written simple hello world application using proton native.
And I'm wondering why `componentWillUnmount` is not called, when:
- I'm doing `Quit`
- Closing main window

Is it by design?
I've pasted console.log in these methods.
`componentDidMount` is working fine.
```
Win10 Node v10.12.0
`-- proton-native@1.1.10
  `-- libui-node@0.2.1
```

**Comment by kusti8** [comment]
When the main window is closed, then the libui loop is immediately stopped and as a result everything stops. There are callbacks, such as [onShouldQuit](https://proton-native.js.org/#/component_APIs/app?id=onshouldquit) for menu and [onClose](https://proton-native.js.org/#/component_APIs/window?id=onclose) for window close. These should do the same things and be more clear than componentWillUnmount.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
