### ISSUE TITLE
Using animations

### ISSUE THREAD

**Issue by badescuga** [kusti8/proton-native#194]
Is there any way we can add animations right now? I'm not seeing anything in the docs

**Comment by mischnic** [comment]
I guess not.
Could you be more specific about 'animations'? Like moving ui elements?

**Comment by kidandcat** [comment]
I'm interested too, yeah, scaling, changing opacity on hover, typical UI animations.

**Comment by kusti8** [comment]
They have to be implemented in libui first.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
