### ISSUE TITLE
Playing audio

### ISSUE THREAD

**Issue by Chivi19** [kusti8/proton-native#195]
Is it possible to have an audio element that plays music from local files, urls, and most importantly streams?

**Comment by mischnic** [comment]
Not "natively", but you can use any npm package to play music and then connect some ui (button and slider or a custom drawn element on `Area`) to control it.

**Comment by kusti8** [comment]
There are many npm packages that provide this, such as https://www.npmjs.com/package/stream-player that can then be connected to the GUI.
