### ISSUE TITLE
Product of "npm run dist" incompatible with node-serialport

### ISSUE THREAD

**Issue by kfatehi** [kusti8/proton-native#196]
Hi I have created an example project here:

https://github.com/kfatehi/proton-native-serialport-issue

This project works fine when working on it with `npm start`

![node_osi1qihxbt](https://user-images.githubusercontent.com/175305/52184745-f42dd700-27cb-11e9-9fb9-eee23b632c62.png)

But when you use `npm run dist` and execute the unpacked or the installed binary, it throws this error:

![protonserialport_dgric9fksq](https://user-images.githubusercontent.com/175305/52184743-f09a5000-27cb-11e9-9fde-96df31f76453.png)

**Comment by kusti8** [comment]
This is more of an electron-builder problem. I suggest you open up an issue there where they can better help you.

**Comment by kfatehi** [comment]
@kusti8 Ok thanks I'll make some noise over there instead.
