### ISSUE TITLE
will proton support hooks?

### ISSUE THREAD

**Issue by joshuarossi** [kusti8/proton-native#200]

**Comment by aviaryan** [comment]
Would absolutely love to use the latest React version with Proton-Native. Btw, can't we use the manual install way of proton-native, use latest react and enjoy hooks? https://proton-native.js.org/#/manual_install

**Comment by kusti8** [comment]
It seems that react-reconciler also needs to be updated to support this. I'll see if I can update it and if that works.

**Comment by talentlessguy** [comment]
@kusti8 is it possible to update the reconciler in the near future? I don't want to write classes :/

**Comment by kusti8** [comment]
It has been updated and hooks work.

**Comment by talentlessguy** [comment]
@kusti8 I tried to make a button that increments counter, but it remains 0, should I open an issue?

here's the code:

```jsx
import React, { useState } from 'react' // import from react

import { Window, App, Button, Text } from 'proton-native' // import the proton-native components

const Example = () => {
  const [counter, count] = useState(0)

  return (
    <App>
      <Window style={{ width: 300, height: 300, backgroundColor: 'red' }}>
        <Text>{counter}</Text>
        <Button title="+1" onClick={() => count(c => c + 1)} />
      </Window>
    </App>
  )
}

export default Example
```

![wtf2](https://user-images.githubusercontent.com/35937217/77689126-34dd4680-6fb2-11ea-9190-642567e85c69.gif)

**Comment by sergiodanilo** [comment]
Change `onClick` to `onPress`
