### ISSUE TITLE
best way to implement auto launch on startup?

### ISSUE THREAD

**Issue by yrik** [kusti8/proton-native#201]
Hello! Thank you for the awesome package.
I'm developing personal activity tracker that would help to remember what I was working some time before and help to prepare invoices. The app should start tracking automatically when the computer starts. It should remain in the tray. 

I have found a package auto-launch, but It's not clear how to specify a path to the running app. I use electron packager. The package automatically takes a `process.execPath` for the electron app. Should it do the same for the react-proton app as well?

Offtop: Does anyone know how to rename the app in the mac os menu after it's being packaged? It shows nodejs instead of the name I used in the package.js.

**Comment by mischnic** [comment]
> I have found a package auto-launch, but It's not clear how to specify a path to the running app. I use electron packager. The package automatically takes a `process.execPath` for the electron app. Should it do the same for the react-proton app as well?

At least for macOS, this path should work:
`path.dirname(process.execPath) + "/YOUR_APP_NAME"`
I don't know about Linux or Windows.

> Offtop: Does anyone know how to rename the app in the mac os menu after it's being packaged? It shows nodejs instead of the name I used in the package.js.

For me, the output generated by electron-builder has this title set to the `name` specified in package.json

**Comment by yrik** [comment]
Thanks.
Eventually, it works for me for mac too with following code

```
const launcher = new AutoLaunch({
    name: 'Tracker App',
    path: process.execPath,
});
```
