### ISSUE TITLE
Showcase on the website

### ISSUE THREAD

**Issue by dimitarnestorov** [kusti8/proton-native#203]
I would love to see some real apps built with Proton Native. Something similar to https://electronjs.org/apps

**Comment by yrik** [comment]
Would like to put https://painlesstracker.com when I can finally build it for windows 
https://github.com/electron-userland/electron-builder/issues/3736

**Comment by sioachim** [comment]
I started a project which is using Proton Native https://gitlab.com/stefan.ioachim/damblagit/tree/develop

**Comment by dyllandry** [comment]
> I started a project which is using Proton Native https://gitlab.com/stefan.ioachim/damblagit/tree/develop

Can you add a readme to your repo to explain your project?

**Comment by sioachim** [comment]
> > I started a project which is using Proton Native https://gitlab.com/stefan.ioachim/damblagit/tree/develop
> 
> Can you add a readme to your repo to explain your project?

The readme is already added to master branch, please access it here : https://gitlab.com/stefan.ioachim/damblagit

Just to be clear, I'm not promoting my project here. My project is just an example of using Proton Native, example which was requested by the user who started this thread.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
