### ISSUE TITLE
Offer a way to start and manage processes

### ISSUE THREAD

**Issue by atrauzzi** [kusti8/proton-native#205]
Does proton native offer any common facility that I can use to create and manage processes from within my applications?

**Comment by mischnic** [comment]
Since proton-native runs on Node, you can use `child_process` as you would in Node:
- https://nodejs.org/api/child_process.html
- http://krasimirtsonev.com/blog/article/Nodejs-managing-child-processes-starting-stopping-exec-spawn

**Comment by atrauzzi** [comment]
Oh, interesting.  So it bundles a nodejs runtime alongside the native application?

**Comment by mischnic** [comment]
> Oh, interesting. So it bundles a nodejs runtime alongside the native application?

No, your code gets actually executed by Nodejs and you call out to native code (a native library).

**Comment by atrauzzi** [comment]
Ah, I see, so this doesn't build on top of react native, though it aims to be compatible?

**Comment by kusti8** [comment]
It aims to be like react native. The API is not compatible with react native due to some limitations, but all JS libraries, including react ones, are compatible.

**Comment by atrauzzi** [comment]
Thanks for the info!
