### ISSUE TITLE
Area.Line not displaying anything

### ISSUE THREAD

**Issue by ranjan-purbey** [kusti8/proton-native#208]
I used the following code:
```
import React, { Component } from 'react';

import { render, Window, App, Area, Text } from 'proton-native';

class Example extends Component {
  render() {
    return (
      <App>
        <Window title="Example" margined={true} menuBar={false}>
          <Area strokeWidth="10">
            <Area.Line x1={10} y1={100} x2={200} y2={100} stroke="blue"/>
          </Area>
        </Window>
      </App>
    );
  }
}

render(<Example />);
```
Output:
![image](https://user-images.githubusercontent.com/6953187/55691391-6c2aa000-59bb-11e9-8c1e-9ef3864e4237.png)
OS: Linux
Node: v11.13.0
proton-native: 1.1.11

**Comment by ranjan-purbey** [comment]
It works if I try to create a path using libui-nodejs directly

**Comment by kusti8** [comment]
Can you try setting the locations as strings instead of integers?

**Comment by mischnic** [comment]
Try putting a box around the area

**Comment by ranjan-purbey** [comment]
@kusti8 Yes, I tried both but didn't work
@mischnic Surrounding by a box made it work. Though, I do not understand, why that is needed. Also if it is required, the official documentation should be updated to say so

**Comment by mischnic** [comment]
It's a Linux bug in libui itself

**Comment by ranjan-purbey** [comment]
We should add this on the manual then, I guess

**Comment by levigideon** [comment]
I was experiencing something similar and I solved it by wrapping the `<Area>` in a `<Box/>`

Have you tried something like this instead?

```
  render() {
    return (
      <App>
        <Window title="Example" margined={true} menuBar={false}>
          <Box>
              <Area strokeWidth="10">
                  <Area.Line x1={10} y1={100} x2={200} y2={100} stroke="blue"/>
              </Area>
           </Box>
        </Window>
      </App>
    );
  }```

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
