### ISSUE TITLE
Is it possible to render elements on top of other elements?

### ISSUE THREAD

**Issue by ranjan-purbey** [kusti8/proton-native#209]
Going through the docs, I couldn't find a way to change the window background. So, I thought to draw a rectangle covering the entire window, and place other components on top of it. But, this will not work as children of a Box are stacked. Is there a way to achieve this? Is absolute positioning supported?

**Comment by ranjan-purbey** [comment]
I need this for a file-explorer app that I am trying to write using proton-native.
![image](https://user-images.githubusercontent.com/6953187/55835131-02d09b80-5b39-11e9-90a6-b7a8eab05e6e.png)
As you can see in the image above, there is a lot of misalignment between icons and text. I think I can solve this if absolute positioning can be achieved. Any help will be appreciated.

**Comment by mischnic** [comment]
Absolute positioning isn't possible, it's not currently implemented in the underlying libui Library: https://github.com/andlabs/libui/pull/332

**Comment by kusti8** [comment]
Once libui adds absolute positioning, then we can add yoga support which should make this a lot easier.
