### ISSUE TITLE
create-proton-app error libui-node@0.2.1 build: `node-gyp configure build`

### ISSUE THREAD

**Issue by randdvorak** [kusti8/proton-native#217]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle libui-node@0.2.1~prebuild: libui-node@0.2.1
6 info lifecycle libui-node@0.2.1~build: libui-node@0.2.1
7 verbose lifecycle libui-node@0.2.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle libui-node@0.2.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/rand/Developer/node_modules/libui-node/node_modules/.bin:/Users/rand/Developer/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/rand/Developer/node_modules/libui-node/node_modules/.bin:/Users/rand/Developer/node_modules/.bin:/Users/rand/narwhal/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/local/bin:/opt/local/sbin
9 verbose lifecycle libui-node@0.2.1~build: CWD: /Users/rand/Developer/node_modules/libui-node
10 silly lifecycle libui-node@0.2.1~build: Args: [ '-c', 'node-gyp configure build' ]
11 silly lifecycle libui-node@0.2.1~build: Returned: code: 1  signal: null
12 info lifecycle libui-node@0.2.1~build: Failed to exec build script
13 verbose stack Error: libui-node@0.2.1 build: `node-gyp configure build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid libui-node@0.2.1
15 verbose cwd /Users/rand/Developer/node_modules/libui-node
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/Cellar/node/12.6.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.6.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error libui-node@0.2.1 build: `node-gyp configure build`
22 error Exit status 1
23 error Failed at the libui-node@0.2.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by randdvorak** [comment]
create-proton-app fails with node 12.  Downgrading to node 10 allows it to build. However, proton-create-app still fails.  rm'ing node_modules and running npm install in the project directory and then it works.  FYI.

**Comment by pcr910303** [comment]
@randdvorak Would you kindly wrap the stack trace into a codeblock?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by immutable-pro** [comment]
This is a full log of 'create-proton-app my-app' on Linux using Node v12.3.1.
[out.log](https://github.com/kusti8/proton-native/files/3458371/out.log)

**Comment by kusti8** [comment]
libui-node has problems with node v12, https://github.com/parro-it/libui-node/issues/134 which seems to be a general problem with nbind: https://github.com/charto/nbind/issues/133

**Comment by quaos** [comment]
Also got this with node 10.15.3 in Windows:

```
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: D:\Programs\Python\Python37\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "D:\\Programs\\nodejs\\node.exe" "D:\\Programs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"      
gyp ERR! cwd D:\Q\Projects\TestReactRedux1\node_modules\libui-node
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qua_o\AppData\Roaming\npm-cache\_logs\2019-09-23T01_16_51_553Z-debug.log
npm WARN rollback Rolling back strip-json-comments@2.0.1 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\Q\Projects\TestReactRedux1\node_modules\rc\node_modules'
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.1 requires a peer of eslint-plugin-flowtype@3.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.    
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta 
|| >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Jarwain** [comment]
@quaos Your error looks like you're trying to use Python3.7 when only python2.7 is supported

**Comment by Reidond** [comment]
Using node 17.10 solved problem

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
