### ISSUE TITLE
Dependency issues on install

### ISSUE THREAD

**Issue by fieldse** [kusti8/proton-native#224]
## **Issue:**
Installing proton-native fails on installing package libui-node@0.2.1

This seems to be a problem with the dependency libui-node.
See issue here:
https://github.com/parro-it/libui-node/issues/132

## Details
- OS: Ubuntu linux 18.10
- Node: v12.8.0

Installed depends:
- build-essential
-  libgtk-3-dev

## Related
 - libui-node: https://github.com/parro-it/libui-node/
 - install issue: https://github.com/parro-it/libui-node/issues/132

## Step to reproduce
1.  Install dependencies above. `sudo apt-get install libgtk-3-dev build-essential`
2. Install create-proton-app. `npm install create-proton-app`

Fails at install step.
`npm ERR! Failed at the libui-node@0.2.1 install script.`

## Stdout log

**Result (npm install proton-native)**
```
Installing packages... This may take a few minutes...
# [snip]
ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR! Failed at the libui-node@0.2.1 install script.
```

**Manually installing `libui-node@0.2.1`**

```
$ npm install -g libui-node@0.2.1

> libui-node@0.2.1 install /usr/local/lib/node_modules/libui-node
> libui-download && autogypi && npm run build

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/libui-node/.libui'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-15T09_33_49_101Z-debug.log
```

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
