### ISSUE TITLE
react-reconciler 0.20.0 + react-dom 16.8

### ISSUE THREAD

**Issue by crshumate** [kusti8/proton-native#225]
`react-reconciler@0.20.0` [does not work with react-dom@16.8.x](https://github.com/facebook/react/issues/14814) as it is missing `schedulePassiveEffects`

`react-dom` is needed to use `react-redux` for `redux` implementations

Updating react-reconciler to 0.21.0 fixes this issue.

Manually changing in `package-lock.json` and using `npm ci` pseudo solves the problem but if you need to install a new package with `npm i ` you have to go back in and edit the package.json file and then re-install with `npm ci` everytime you want to add a new npm package.

Easier change would be just to update it to react-reconciler@0.21.0

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
