### ISSUE TITLE
Could not create project, error ELIFECYCLE, failed at libui-node install script

### ISSUE THREAD

**Issue by y-sumanth** [kusti8/proton-native#226]
Here is log:
`16978 error code ELIFECYCLE`
`16979 error errno 1`
`16980 error libui-node@0.2.1 install: "libui-download && autogypi && npm run build"`
`16980 error Exit status 1`
`16981 error Failed at the libui-node@0.2.1 install script.`
`16981 error This is probably not a problem with npm. There is likely additional logging output above.`

Thank you..

**Comment by leonps531** [comment]
I am getting the same error.

**Comment by chloeXu96** [comment]
same here, please help

**Comment by JavaScriptDude** [comment]
This error appears to be related to Node v12. Can you confirm the version you are using?

I've been able to get create-proton-app working as per Quick Start guide using Node v8.16.1. It does not work on v10.16.3 LTS or beyond.

However, I was able to get the demo apps working using Node v10.16.3 LTS by following the [Old Manual instructions](https://proton-native.js.org/#/manual_install).

**Comment by JavaScriptDude** [comment]
Just tested and was able to get the demo notepad app working using node v11.15.0. 

So it looks like the last Node versions that can be used  are:
 - create-proton-app: Node v8.16.1
 - manual method: Node v11.15.0

Hope this helps someone.

**Comment by apollolux** [comment]
Likely also relevant libui-node issues: [132](https://github.com/parro-it/libui-node/issues/132#issuecomment-561262428) and [142](https://github.com/parro-it/libui-node/issues/142#issuecomment-554957822) (which links to [bcoin-org/bcrypto#7](https://github.com/bcoin-org/bcrypto/issues/7) which might have the useful solution)

Solution might be to update libui-node to use v12 compatible compilation like the bcrypto issue did.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.

**Comment by JavaScriptDude** [comment]
Tested proton-native v2 on Node v12.14.1 on Ubuntu 18.04 and works great. 

FYI, I had Node v10.16.3 installed and this worked ok also. Node v8.9.4 fails.

Thanks for the excellent work!
