### ISSUE TITLE
create-proton-app fail with errors

### ISSUE THREAD

**Issue by chloeXu96** [kusti8/proton-native#231]
I tried to install and create a new proton app, but there are errors occurred and fail to create
I did install create-proton-app globally, after I run `create-proton-app my-app`, it results in 

`gyp
ERR! build error

gyp
 ERR! stack Error: `make` failed with exit code: 2
gyp
 ERR! stack     at ChildProcess.onExit (/Users/chloexu/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp 
ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack
     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)

gyp
 ERR! System Darwin 18.7.0

gyp ERR! command "/Users/chloexu/.nvm/versions/node/v12.2.0/bin/node" "/Users/chloexu/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp 
ERR! cwd /Users/chloexu/Desktop/my-app/node_modules/libui-node
gyp ERR! node -v
 v12.2.0
gyp ERR! node-gyp -v v3.8.0

gyp
 ERR! not ok 

npm ERR!
 code ELIFECYCLE
npm ERR! errno 1

npm ERR! libui-node@0.2.1 build: `node-gyp configure build`

npm ERR! Exit status 1
npm ERR! 
npm ERR!
 Failed at the libui-node@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm
 WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chloexu/.npm/_logs/2019-09-26T19_02_00_892Z-debug.log

npm ERR! 
code ELIFECYCLE
npm ERR! errno 1

npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm
 ERR! Exit status 1
npm ERR! 
npm ERR!
 Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm
 ERR!     /Users/chloexu/.npm/_logs/2019-09-26T19_02_01_291Z-debug.log

An error ocurred: 
 npm install has failed.
`

**Comment by HighDeck** [comment]
Same error here. I read there was issues concerning proton-native with Node 12 (related with nbind module).  Any update on this ?
You might want to downgrade to Node 10 to make it work
Cheers!

**Comment by coreyphillips** [comment]
@chloeXu96, using nvm I downgraded node to v8 `nvm use 8`. Afterwards,  `npm install -g create-proton-app` & `create-proton-app my-app` resulted in a successful install and project build for me.

**Comment by bndby** [comment]
Same problen on Linux Mint, node 10 & 12, gtk 3.0 installed

```
npx create-proton-app proton-desktop
npx: installed 3 in 1.344s
Creating a new Proton Native app on /var/www/html/proton-desktop

Installing packages... This may take a few minutes. 

npm WARN
 deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.


> libui-node@0.2.1 install /var/www/html/proton-desktop/node_modules/libui-node
> libui-download && autogypi && npm run build


Downloaded zip: /home/p12/.libui/libui-shared-linux-x64-alpha3.5-master-008.tar.gz

Libui binaries extracted to: /var/www/html/proton-desktop/node_modules/libui-node


> libui-node@0.2.1 build /var/www/html/proton-desktop/node_modules/libui-node
> node-gyp configure build


Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found

gyp: Call to 'pkg-config gtk+-3.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp

gyp
 ERR! 
configure error 

gyp 
ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR!
 stack     at ChildProcess.onCpExit (/home/p12/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR!
 stack     at ChildProcess.emit (events.js:198:13)
gyp ERR!
 stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

gyp 
ERR! System Linux 4.15.0-70-generic

gyp ERR!
 command "/home/p12/.nvm/versions/node/v10.17.0/bin/node" "/home/p12/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp
 ERR! cwd /var/www/html/proton-desktop/node_modules/libui-node

gyp ERR! 
node -v v10.17.0
gyp ERR!
 node-gyp -v v5.0.3
gyp
 ERR! not ok 

npm
 ERR! code ELIFECYCLE

npm 
ERR! errno 1

npm 
ERR! libui-node@0.2.1 build: `node-gyp configure build`
npm ERR! Exit status 1

npm
 ERR! 
npm
 ERR! Failed at the libui-node@0.2.1 build script.
npm 
ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm 
WARN Local package.json exists, but node_modules missing, did you mean to install?



npm ERR! A complete log of this run can be found in:
npm ERR!
     /home/p12/.npm/_logs/2019-12-06T05_47_03_252Z-debug.log

npm 
WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})



npm ERR!
 code ELIFECYCLE

npm ERR!
 errno 1

npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm 
ERR! Exit status 1

npm ERR!
 
npm ERR! Failed at the libui-node@0.2.1 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:
npm ERR!     /home/p12/.npm/_logs/2019-12-06T05_47_03_768Z-debug.log


An error ocurred: 
 npm install has failed.

```

**Comment by michaelzoidl** [comment]
Same with node `v12.13.1 (LTS)` and i tried using `v10.16.3`. Both are failing with the above mentioned errors.

With the `v8.16.2` it worked fine. Is there any chance this will get updated soon?

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.

**Comment by michaelzoidl** [comment]
Hm, i just reinstalled `proton-native` and created a test project with `proton-native init XXX`

It shows no error, but that it cant create a window:

```cli
λ hello-world npm run start
> hello-world@0.0.1 start /Users/michaelzoidl/Code/hello-world
> babel-node index.js

no screens available, assuming 24-bit color
Cannot create window: no screens available
[1]    34340 abort      npm run start
```

I tried it with node `v12.13.1` and proton-native `v0.0.7`

```cli
λ hello-world proton-native -v              
proton-native-cli/0.0.7 darwin-x64 node-v12.13.1
```


Did i understand something wrong that the node version 12.13.1 does not work or should it work with this version?

Do you need more informations? :) 

Thanks for your contribution and time you invest in this project!

**Comment by kusti8** [comment]
On Mac, there is a bug for Node versions that are greater than and equal to 12.13.1. I suggest you downgrade using NVM. Also in the future please create a new issue.

**Comment by marsinearth** [comment]
On the document website, it's written [Proton Native does not work on Macs with Node versions >12.13.1 and >13.0.1.](https://proton-native.js.org/#/quickstart?id=install). It causes confusion so modifying it to `...with Node versions >= 12.13.1` to be much clearer.
