### ISSUE TITLE
Installation and Styling...

### ISSUE THREAD

**Issue by TahorSuiJuris** [kusti8/proton-native#232]
I had the same issues as others for installation.  Followed:  https://www.freecodecamp.org/news/build-native-desktop-apps-with-javascript-a49ede90d8e9/ which was a bit clearer.

Q.  Is it still not possible for UI customizations (styling)?

**Comment by kusti8** [comment]
V2 supports styling and that is being released very soon. V1 does not support styling.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
