### ISSUE TITLE
Keep application on top

### ISSUE THREAD

**Issue by lacymorrow** [kusti8/proton-native#234]
In essence I want to display a transparent PNG above all other applications, and it remains at the forefront of the screen, even after losing focus.

Is there something similar to QT's `WindowStaysOnTopHint` for proton-native?

**Comment by kusti8** [comment]
Not right now. V2 is moving to Qt, so that could be implemented later on.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
