### ISSUE TITLE
Is Proton native support webview tag?

### ISSUE THREAD

**Issue by ken30huang** [kusti8/proton-native#236]
Is Proton native support webview tag?

I want to do some thing , like I click a button and then open a website in my desktop app（without iframe tag），some thing like a browser.

I can't find any infomation in document page.

**Comment by lacymorrow** [comment]
Proton native does not currently support a webview component

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
