### ISSUE TITLE
Window resize unexpected behavior

### ISSUE THREAD

**Issue by ErAz7** [kusti8/proton-native#253]
**Describe the bug**
App window flickers and jumps to left top corner on resize

**To Reproduce**
 just `npx proton-native-cli init my-app` and `npm start`

**Expected behavior**
window resizes like other apps.

**Screenshots**

**Versions:**
 - OS: windows
 - Version: 10
 - Node version:: 12.3.1

**Screen Record Link:**
https://vimeo.com/386538239

**Comment by pcr910303** [comment]
Looks like a duplicate of #246 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ErAz7** [comment]
Yeah, the exact same issue, so I close this
