### ISSUE TITLE
Document usability of Node.js packages

### ISSUE THREAD

**Issue by benwiley4000** [kusti8/proton-native#26]
My biggest question going into this is whether any arbitrary Node.js package (including native bindings) can be required and used as with Electron. Based on [this example](https://github.com/kusti8/proton-native/blob/master/examples/Notepad/index.js#L2) which uses `fs` I believe that's the case. If so, that may be worth documenting in the list of "Features" (makes a difference for me if I have access to [Node implementations](https://github.com/audiojs/web-audio-api) of browser JS APIs like web audio).

**Comment by parro-it** [comment]
See #20 
TLDR: yes, you can use node modules. 
I also think that a small remark in documentation would be useful...
