### ISSUE TITLE
Multi Target Example

### ISSUE THREAD

**Issue by xavier7179** [kusti8/proton-native#263]
It would be great if you could deliver at least one of the actual examples, e.g. the calculator, to deliver building also for mobile (react-native) and web

**Comment by kusti8** [comment]
This isn't meant to be multi target. If you take the code around `<Window>` and `</Window>' and paste it into React Native, it should work, but that is not the primary focus.

**Comment by xavier7179** [comment]
I understand your point but consider this: what is the point of having a support for desktop deployment that is closed to React Native if you are not developing multi-platform in smart (time saving) ways?
