### ISSUE TITLE
TypeError: Cannot read property 'setParent' of undefined

### ISSUE THREAD

**Issue by giovanniKleinCampigoto** [kusti8/proton-native#269]
**Describe the bug**
When I'm importing a Button from proton-native, and rendering it the app crashes, with the error:
TypeError: Cannot read property 'setParent' of undefined.

**To Reproduce**
```jsx
import { Button } from 'proton-native';

return (
    <App>
      <Window style={{ width: 700, height: 768, backgroundColor: 'white' }}>
        <View>
          <Text style={processStyle}>aksjdhahdjk</Text>
          <Button>Click</Button>
        </View>
      </Window>
    </App>
  );
```

**Expected behavior**
Button should be rendered with sucess.

**Screenshots**
![Captura de tela de 2020-02-26 16-12-41](https://user-images.githubusercontent.com/23245646/75378776-0e44c680-58b3-11ea-850d-5c4127aa26f7.png)

**Versions:**
 - OS: Ubuntu
 - Version 19.04
 - Node version v12.14.1

**Additional context**

**Comment by olingern** [comment]
Also having the same problem on Arch linux and Node 12.14.1

**Comment by olingern** [comment]
Not sure why, but working from the [examples](https://github.com/kusti8/proton-native/tree/master/examples) I'm able to compile.

**Comment by jcolag** [comment]
I'm obviously not the expert, but it looks like you _may_ need to `import { App, Button View, Text, Window } from 'proton-native'` instead of just `Button`, to get the application running.

**Comment by giovanniKleinCampigoto** [comment]
> I'm obviously not the expert, but it looks like you _may_ need to `import { App, Button View, Text, Window } from 'proton-native'` instead of just `Button`, to get the application running.

Thanks for the heads up, but everything is imported, it's just a snippet.

**Comment by kusti8** [comment]
As seen [here](https://reactnative.dev/docs/button), Button takes no children. To pass the text to the button, you can use the `title` prop. I've added an error that should make this clearer in the future.
