### ISSUE TITLE
Please add the default values to properties in the documentation

### ISSUE THREAD

**Issue by Kilian** [kusti8/proton-native#29]
For example, Box has a property 'vertical', which is `true` when not specified. This is not made clear in the documentation: https://proton-native.js.org/#/component_APIs/box?id=vertical 

I would expect an additional column in the reference tables called "default", which e.g. for vertical would show `true`,  and for padded would show `false`.

**Comment by kusti8** [comment]
Yeah, I will do that when I get a chance.
