### ISSUE TITLE
continuation

### ISSUE THREAD

**Issue by anubra266** [kusti8/proton-native#312]
@kusti8  There hasn't been any commits in a long time. 
I just wanted you to know, that there's a large community by your side, whatever you need;
Sponsors, code contribution. We're here.
So please don't give up on this. 
Ask and we shall give.

**Comment by TheRafaelFarias** [comment]
I think someone with time does a fork will be better, he doesn't respond to anyone on any issues

**Comment by ArashMM** [comment]
This project had a great potential

**Comment by aramodi** [comment]
So me and a few others are trying to maintain Proton Native in a fork called [Valence Native](https://github.com/valence-native/valence-native). PRs are welcome :)

**Comment by TheRafaelFarias** [comment]
> So me and a few others are trying to maintain Proton Native in a fork called [Valence Native](https://github.com/valence-native/valence-native). PRs are welcome :)

 Would be cool if you added issues in Valence Native

**Comment by aramodi** [comment]
Good idea. Will do. :)
