### ISSUE TITLE
Will anyone ever make a fork of this repo?

### ISSUE THREAD

**Issue by aramodi** [kusti8/proton-native#318]
It seems like this project is unmaintained. If someone would have the time and motivation to make a fork and manage it, I think we as a community could maintain it. This project has a great potential, we just need to maintain it!

**Comment by rockiger** [comment]
Would it make sense to create an organization for that?

**Comment by aramodi** [comment]
In my opinion, yes, it would!

**Comment by aramodi** [comment]
@rockiger Would you be interested in joining that (yet non-existent) organization?

**Comment by kusti8** [comment]
I am sorry about it, but I have been overloaded with work and other projects. I am happy to move to an organization when you set it up and transfer ownership.

**Comment by rockiger** [comment]
> @rockiger Would you be interested in joining that (yet non-existent) organization?

Yes, I would, but I am wondering if https://github.com/nodegui/react-nodegui does fill the same niche.

**Comment by aramodi** [comment]
react-nodegui is not production ready

**Comment by aramodi** [comment]
There you go: https://github.com/proton-nativejs/proton-native
Who wants to join?

**Comment by aramodi** [comment]
@kusti8 Am I allowed to use this logo as the organization profile picture? Also, am I allowed to use the logo for the future (again, yet non-existent) discord server?

**Comment by rockiger** [comment]
I will join

> There you go: https://github.com/proton-nativejs/proton-native
> Who wants to join?

I will.

**Comment by aramodi** [comment]
I invited you :)

**Comment by kusti8** [comment]
> 
> 
> @kusti8 Am I allowed to use this logo as the organization profile picture? Also, am I allowed to use the logo for the future (again, yet non-existent) discord server?

Yes you're allowed. I will archive this project in a couple days.

**Comment by aramodi** [comment]
Thank you

**Comment by aramodi** [comment]
Here's the permanent invite link: https://discord.gg/9rP6x9Vy3m
Anyone is welcome to join! :)

**Comment by aramodi** [comment]
@rockiger Do you have Discord?

**Comment by MatthewScholefield** [comment]
@aramodi Can you delete/rename your fork at https://github.com/proton-nativejs/proton-native ? Then, @kusti8 can transfer this repo into the new `proton-nativejs` organization.

I think it's super important to do a proper transfer to prevent confusion and to ensure all the PRs remain open (and all the 10k stars remain on the repo).

**Comment by aramodi** [comment]
Hey, that's a good idea!

**Comment by aramodi** [comment]
I have renamed the fork and organization to [Valence Native](https://github.com/valence-native/valence-native) @kusti8 would you please update the README.md?
