### ISSUE TITLE
create-proton-app

### ISSUE THREAD

**Issue by albe-rosado** [kusti8/proton-native#33]
Hey mates. I'm working on a  cli plugin [create-proton-app](https://github.com/albe-rosado/create-proton-app) to start a Proton Native app with a simple template. Is currently functional, may have bugs but still in its first days. @kusti8  thanks for this project! Also, I would like to know if there is an IRC channel or somewhere else where people interested in this project could meet.

**Comment by kusti8** [comment]
Currently, there isn't a chat. If you would like to create one, that's fine by me! create-proton-app looks great, nice design! Thanks!

**Comment by thinklinux** [comment]
I think the best place for a channel would be in the discord react community. That's the link for it https://discord.gg/hRFPcy and inside it should be possible to make a channel for proton.

**Comment by albe-rosado** [comment]
Or create one for this project itself, this project goes beyond React in my opinion. I just created this one https://gitter.im/Proton-Native, and invited you two @kusti8 and @thinklinux , i will make a PR for the docs to provide the [chat link](https://gitter.im/Proton-Native).

**Comment by kusti8** [comment]
I've merged it. Closing
