### ISSUE TITLE
Bundle

### ISSUE THREAD

**Issue by GordyGordy** [kusti8/proton-native#39]
I was with you until I got to your bundle section in the docs. This is the all import bit really.

"Currently, the easiest way is to simply download a node binary for your platform, copy it into your project root. Then create a shortcut/script to execute that.

Make sure you have babel transpile it, in case you use any new syntax not supported by your current version of node."

Ok downloaded node-v8.9.4-darwin-x64.tar.gz and copied to root. Do I unzip. Create what shortcut to where and then place shortcut where? Make sure you "babel transpile it", do what????

Hope you can make that clearer, I'm a react developer.

**Comment by albe-rosado** [comment]
Hi @GordyGordy , as you know Javascript is an interpreted language that needs an engine(SpiderMonkey, V8,...) to run your script files. What he meant was that if you need something more "standalone"-ish, you can download the node binaries for your platform and make a *.sh (or *.bat in Windows?) file where you point the node binary to your project entry files ( index.js ) so could execute it like `./run.sh` for example. Using babel you can bundle your app in a more compact and light files, same as you were to serve it in a website. You can also use  [nexe](https://github.com/nexe/nexe) to do the packaging work for you. Hope it helps. Have a great weekend!

**Comment by kusti8** [comment]
I've explained it more after that paragraph. That just serves to give an overview. So basically run `npm run build`, then unzip it, follow the picture if on Windows or the script if on Linux/Mac and you should be done. I'll try and clear it up a bit though.

**Comment by GordyGordy** [comment]
Thanks for getting back to me guys. Maybe I'm expecting the wrong thing. I extracted node into the root of my project and then ran build. I was expecting a .app file to be built or something, like electron. Think I must be misunderstanding this project. I'll keep watching to see how things progress.
