### ISSUE TITLE
Issue Installing Ubuntu 16.04

### ISSUE THREAD

**Issue by mathewjpotter** [kusti8/proton-native#45]
During an install on Linux, This is the error it gave, any insight would be great

npm WARN optional dep failed, continuing fsevents@1.1.3
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
-
> libui-node@0.0.12 install /home/mp/node_modules/proton-native/node_modules/libui-node
> libui-download && autogypi && npm run build && npm run copy-node

Downloaded zip: /home/mp/.libui/libui-shared-linux-x64-pre11.alpha.4.tar.gz
Libui binaries extracted to: /home/mp/node_modules/proton-native/node_modules/libui-node
module.js:327
    throw err;
    ^

Error: Cannot find module 'dezalgo'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mp/node_modules/npm/lib/utils/correct-mkdir.js:2:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Linux 4.14.0-041400-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-S" "proton-native"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! libui-node@0.0.12 install: `libui-download && autogypi && npm run build && npm run copy-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.0.12 install script 'libui-download && autogypi && npm run build && npm run copy-node'.
npm ERR! This is most likely a problem with the libui-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     libui-download && autogypi && npm run build && npm run copy-node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libui-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls libui-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mp/npm-debug.log

**Comment by swiftmedia** [comment]
I think this is related to node version

**Comment by albe-rosado** [comment]
@swiftmedia are you using the cli tool (create-proton-app)?

**Comment by albe-rosado** [comment]
Also please make sure you installed all [dependencies](https://proton-native.js.org/#/quickstart?id=linux) for Linux.

**Comment by swiftmedia** [comment]
Yes it was dependencies issue, and also a node.js version issue as well :)
all resolved, cool stuff works good
