### ISSUE TITLE
Question: Material-UI

### ISSUE THREAD

**Issue by WickedSik** [kusti8/proton-native#53]
Would it be possible to use `material-ui` or `react-native-material-ui` in `proton-native` ?

If no, what would be the challenge into creating this?
If yes, why doesn't it work? 😢 

Or should I actually use `react-native-material-ui` instead of `material-ui`, because that would make sense!

**Comment by albe-rosado** [comment]
Proton-native leverages libui-node library that implements nodejs bindings to native widgets toolkit across platforms, to my knowledge, there is not styling on libui-node, so not styling here either. See https://github.com/kusti8/proton-native/issues/51

**Comment by WickedSik** [comment]
Understood. I had a different view of this project, but what you say makes perfect sense.

Thanks for the information!
