### ISSUE TITLE
Use upstream libui-node

### ISSUE THREAD

**Issue by mischnic** [kusti8/proton-native#54]
The upstream libui-node master should now equal your fork (`$ORIGIN` rpath on linux and copying `nbind.node` to the root folder), but it also sets the rpath correctly for macOS.

https://github.com/kusti8/proton-native/blob/7741dd2fccbce773ce4bea709fef30b2773e82d5/package.json#L36

**Comment by kusti8** [comment]
Ok looks good. Did you increment the version a d publish to npm because I didn't see that in your diffs.

**Comment by mischnic** [comment]
@parro-it ?

**Comment by parro-it** [comment]
Just released 0.1.0 on npm. 
I'm testing now with my fork of proton... I will publish a PR here.

**Comment by mischnic** [comment]
@parro-it This can get you started: https://github.com/mischnic/proton-native/commit/d42ab2b7319b5fdd3612b5f8c8ec27b4613c416c

**Comment by parro-it** [comment]
Oh great! if you open a PR here of your forks I'll push further changes there (I don't know if I need specific permission to do so)

**Comment by kusti8** [comment]
Does libui not need to be initialized anymore ? I noticed that was taken out in the fork.

**Comment by parro-it** [comment]
Any idea why I get Electron installed when I `npm install` proton?

![image](https://user-images.githubusercontent.com/11197111/37615721-3f5e5f58-2bae-11e8-8868-671a08337216.png)

Electron is not a direct proton dependency AFAIK

**Comment by parro-it** [comment]
> Does libui not need to be initialized anymore ? I noticed that was taken out in the fork.

No, init is now called automatically the first time you require the module. We'll have to update docs & examples

**Comment by mischnic** [comment]
Not of proton, but the react dev tools:
https://github.com/kusti8/proton-native/blob/57896ffed96188a40328b4239858a110f395b1f6/package.json#L50

@kusti8 How does integration with the dev tools work? This doesn't: https://github.com/kusti8/proton-native/blob/e10f4818611e7f61261865678e127cd6bd56c3c8/src/render/index.js#L17-L22
---
PR: https://github.com/kusti8/proton-native/pull/57

**Comment by kusti8** [comment]
I used to use the dev tools to debug some of the code that wasn't working.
It isn't strictly necessary anymore.

**Comment by mischnic** [comment]
I tried commenting out these lines and the dev tools started by `npx react-dev-tool` didn't connect to proton.

**Comment by parro-it** [comment]
It's working 🎉

![image](https://user-images.githubusercontent.com/11197111/37616913-affdcf84-2bb1-11e8-82c4-652a8fdbc895.png)

@mischnic I pushed to your fork
