### ISSUE TITLE
Grid does not work on macOS

### ISSUE THREAD

**Issue by maximecolin** [kusti8/proton-native#55]
I tried the [Grid example given in the doc](https://proton-native.js.org/#/component_APIs/grid). I guess the two components should be displayed one next to the other, but only the first cell is displayed.

![capture d ecran 2018-03-17 a 16 50 21](https://user-images.githubusercontent.com/606766/37557431-d417f6e6-2a04-11e8-826f-8772dbffce25.jpg)

**Comment by mischnic** [comment]
Works on Windows 10

**Comment by andlabs** [comment]
Grid does work on macOS; it's just insanely buggy because Auto Layout is hard, so it only works under specific circumstances... This is an active problem. What should that example look like?

**Comment by mischnic** [comment]
Windows 10: 
![unbenannt](https://user-images.githubusercontent.com/4586894/37612067-64c16402-2ba4-11e8-9073-9d0708c1f201.PNG)

**Comment by kusti8** [comment]
@andlabs I don't know if it would be easier, but yoga is an option as well for layout similar to grid (css introduced flexbox because grids became cumbersome).

**Comment by mischnic** [comment]
> css introduced flexbox because grids became cumbersome

Actually, flexbox came first because tables were too cumbersome 😄. CSS Grid Layout is the newest of them all.

**Comment by shayneoneill** [comment]
Was a solution ever found? Its bit of a show stopper

**Comment by andlabs** [comment]
The proper solution would be to fix Grid. There is the idea of using Yoga, but that would require not only a third party dependency but also a fixed view. I'm not sure if I want to include that in libui for reasons I have to explain in detail, but I'm not sure what prevents one from being written outside of libui itself.

**Comment by mischnic** [comment]
> I'm not sure if I want to include that in libui for reasons I have to explain in detail, but I'm not sure what prevents one from being written outside of libui itself.

With a fixed view in libui, Yoga can be implement on the javascript side (as already done in https://github.com/kusti8/proton-native/pull/76). What do you mean by "one from being written outside of libui itself" - the fixed view or yoga?

**Comment by andlabs** [comment]
Does proton-native have any C code other than libui?

**Comment by mischnic** [comment]
Proton-native itself has no native code at all, it's just another Javascript wrapper around libui-node.

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.

**Comment by andlabs** [comment]
(If you actually fixed these issues please push them upstream; I'll be writing a test suite to ensure things don't fall apart)

**Comment by mischnic** [comment]
(V2 uses a purpose-built Qt binding instead of libui[-node].)

**Comment by andlabs** [comment]
Very well, thanks in the meantime!
