### ISSUE TITLE
Standard menu item are showed are checkbox menu.

### ISSUE THREAD

**Issue by parro-it** [kusti8/proton-native#58]
It appears that they are added as standard menu item,
but then switched to check when `checked` property is set to default value of `false` here: https://github.com/kusti8/proton-native/blob/master/src/components/MenuBar.js#L74

Commenting this line make menu items appear as they should.
I don't know why `libui` change the menu item type once constructed, anyway, seems better to just remove the property setting on proton side, since a default menu item does not have the prop.

**Comment by parro-it** [comment]
Should be solved by #57

**Comment by kusti8** [comment]
Interesting. Thanks.

**Comment by mischnic** [comment]
Basically the same problem as with https://github.com/kusti8/proton-native/pull/56.
