### ISSUE TITLE
stretchy={false} not working

### ISSUE THREAD

**Issue by Boomxx** [kusti8/proton-native#6]
The universal prop `stretchy` doesn't seem to be working for me with the following versions:

```
  "dependencies": {
    "proton-native": "^1.0.9",
    "react": "^16.2.0"
  },
```

`TextInput, Button, Box` for example always fill the available space regardless of adding `stretchy={false}`.

I also was unable to find out how to position and size components - is that somewhere in the docs that I missed?

**Comment by kusti8** [comment]
Can you paste your code?

**Comment by Boomxx** [comment]
Sure, I have just been trying the examples out and seeing the issue:

```
import React, { Component } from 'react';

import { render, Window, App, TextInput, Dialog } from 'proton-native';

class Example extends Component {
  render() {
    return (
      <App>
        <Window title="Example" height={500} width={500}>
          <TextInput
            stretchy={false}
            onChanged={() => Dialog('Error', { title: 'Message' })}
          />
        </Window>
      </App>
    );
  }
}

render(<Example />);
```

**Comment by kusti8** [comment]
When you only have a single child in a window, then you can't use stretchy.
You need to have a box in the window, and then the text input inside the
box. Was this in my documentation ? If so could you link it so I can fix it?

**Comment by Boomxx** [comment]
https://proton-native.js.org/#/methods/dialog

**Comment by kusti8** [comment]
Ok thank you I'll fix that now.

**Comment by Boomxx** [comment]
![image](https://user-images.githubusercontent.com/13614959/36288103-12e11410-1287-11e8-995a-fb3a46ec06bd.png)

Is this the expected result with `stretchy={false`}?

```
import React, { Component } from 'react';

import {
  render,
  Window,
  App,
  TextInput,
  Dialog,
  Button,
  Box,
} from 'proton-native';

class Example extends Component {
  render() {
    return (
      <App>
        <Window title="Example" height={500} width={500}>
          <Box>
            <Button stretchy={false}>Button</Button>
            <TextInput
              stretchy={false}
              onChanged={() => Dialog('Error', { title: 'Message' })}
            />
          </Box>
        </Window>
      </App>
    );
  }
}

render(<Example />);

```

**Comment by kusti8** [comment]
Yes it is. You can't set the size of the objects unfortunately, that's just
how libui is. You can add separators or make it all a grid if you want.

**Comment by Boomxx** [comment]
okay great thanks - just wanted to make sure I wasn't messing anything up
