### ISSUE TITLE
Window can have only one child

### ISSUE THREAD

**Issue by mischnic** [kusti8/proton-native#66]
https://github.com/parro-it/libui-node/blob/master/docs/window.md#setchild:
> **`setChild`**
Allow to specify the control to show in window content area. UiWindow instances could contains only one control. If you need more, you have to use Containers.

This
```jsx
<App>
  <Window title="Test" size={{ w: 500, h: 500 }} margined={true}>
    <Text>Input:</Text>
    <Box>
      <Button>Hello</Button>
      <TextInput />
    </Box>
    <Button>Test</Button>
  </Window>
</App>
```
will display only:
```jsx
<Button>Test</Button>
```
(the last child).

This should be documented and even better a warning/error be shown.

**Comment by kusti8** [comment]
Ok I'll add a warning.

**Comment by mischnic** [comment]
(Same goes for Group)
