### ISSUE TITLE
Newline in Text

### ISSUE THREAD

**Issue by mischnic** [kusti8/proton-native#68]
libui correctly displays literal newline characters (`\n`) in labels.
This works:

```jsx
<Text stretchy={false}>{"AutoUpdate sucht nach Updateversionen der Microsoft-Software. Weitere Informationen zu \n AutoUpdate finden sie in der Hilfe."}</Text> 
```

This doesn't:

```jsx
<Text stretchy={false}>AutoUpdate sucht nach Updateversionen der Microsoft-Software. Weitere Informationen zu {'\n'} AutoUpdate finden sie in der Hilfe.</Text> 
```

Results in some extra commas and an error message: `text , <line break>, text`
```
$ npx babel-node app.js
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Text`, expected `string`.
$
```
![bildschirmfoto 2018-03-23 um 16 34 32](https://user-images.githubusercontent.com/4586894/37838443-29389376-2eb8-11e8-8905-ccc85b834401.png)

So the children array needs to be properly joined when rendering.

**Comment by baona95** [comment]
@mischnic You have to do it React way like this

```<Text>{`
Line 1
Line 2
`}</Text>```

**Comment by mischnic** [comment]
Yes, that works (see the first code snippet above).

First result for "react native newline":
```jsx
<Text>
Hi~{"\n"}
this is a test message.
</Text>
```

In normal React, it would be `<br/>`.

**Comment by kusti8** [comment]
I don't think I'm going to fix this. It's better in my opinion to do it as a simple multiline string, rather than that way.

**Comment by parro-it** [comment]
> I don't think I'm going to fix this. It's better in my opinion to do it as a simple multiline string, rather than that way.

How do you plan to manage non-hard lines break and indentation?

**Comment by kusti8** [comment]
In libui-node there isn't a way to wrap text right? And as for indenting the \t works fine.
```jsx
<Text>{"123\t456"}</Text>
```

**Comment by parro-it** [comment]
> In libui-node there isn't a way to wrap text right?

Not at the moment, but there is an `uiNewMultilineEntry`function that should return a wrappable multine text entry (I'm currently using `uiNewNonWrappingMultilineEntry`).

I'll add binding for that.

**Comment by parro-it** [comment]
see https://github.com/parro-it/libui-node/issues/85
