### ISSUE TITLE
Menu Buttons not working (Quit, About, Preferences)

### ISSUE THREAD

**Issue by MarkRabey** [kusti8/proton-native#71]
Setting `type` on `Menu.Item` to `Quit`, `About`, or `Preference` does not have the desired effect. The items do not appear in the menu. When `Quit` is used, using Command+Q _does_ quit the app. So, it's at least partly working I suppose.

The issue also exists in the sample Notepad app.

**Comment by mischnic** [comment]
Is that on macOS, Windows or Linux?

**Comment by MarkRabey** [comment]
Sorry, I'm on Mac.

**Comment by mischnic** [comment]
On Mac, these items go into the application menu:

without `About` and `Preferences`
![bildschirmfoto 2018-03-29 um 16 37 18](https://user-images.githubusercontent.com/4586894/38094973-8bc99eca-336f-11e8-8a9e-54ae2832f54a.png)

with them:
![bildschirmfoto 2018-03-29 um 16 37 35](https://user-images.githubusercontent.com/4586894/38094974-8bedf3e2-336f-11e8-8c09-16654fdd5870.png)

**Comment by MarkRabey** [comment]
Wow! Just like every other Mac app! No idea how I missed that...LOL Thanks!

**Comment by sirajulm** [comment]
@mischnic Thank you for the solution. But I dont find a way to change the title of About Menu Item, it still shows `About node`. Tried adding text as `children`, and tried attributes, `title` and `label`, but it didnt help.
