### ISSUE TITLE
Window size not working properly

### ISSUE THREAD

**Issue by zaguini** [kusti8/proton-native#8]
Hi! Awesome library!

I don't know how the `libui-node` works properly, so please help.

If I render a `<Window />` element on the tree, without any children, the `Window` get the right size. But, as soon as I insert the children, the window fits to the children and ignore the specified width and height. Is it expected?

Also, it looks like updating the `height` of the window via state doesn't work as well. My code is the following:

```js
import React, { Component } from 'react'

import { render, Window, App, Button } from 'proton-native'

class Example extends Component {
  state = {
    height: 300,
  }

  componentWillMount() {
    this.handleResize = this._handleResize.bind(this)
  }

  _handleResize() {
    this.setState({
      height: 400,
    })
  }

  render() {
    console.log(this.state.height)

    return (
      <App>
        <Window
          title="Example"
          margined
          size={{
            w: 300,
            h: this.state.height
          }}
        >
          <Button onClicked={this.handleResize}>
            Change my size!
          </Button>
        </Window>
      </App>
    )
  }
}

render(<Example />)
```

**Comment by kusti8** [comment]
Is this on Mac?

**Comment by zaguini** [comment]
Yes.

**Comment by kusti8** [comment]
I think that's just how Mac works. I don't think it has stretchy components. There's nothing I can do about that.

**Comment by zaguini** [comment]
But I don't want stretchy components... I want the Window to be with the size I defined, and that's not what's happening.

**Comment by kusti8** [comment]
Try adding a box and then the button inside the box.

**Comment by andlabs** [comment]
Yes, buttons on macOS have a fixed height, and by default are programmed to resist growing vertically. Sorry about that. If you set the `contentHuggingPriority` in `NSUserInterfaceLayoutOrientationVertical` to `NSLayoutPriorityDefaultLow` you'll be able to grow the window vertically, but the button will stay somewhat centered in the window; it won't grow vertically (and that's a thing with AppKit that I can't do anything about).

**Comment by montanaflynn** [comment]
I think this should be opened back up, it certainly seems like a bug when it happens. If it really can't be fixed then a note should be put in the docs.

**Comment by andlabs** [comment]
There are a lot of other issues with resizing on Mac that I need to fix as well (and these are issues on my end due to probably not using Auto Layout correctly), so the answer to these questions will likely be a case-by-case thing until I fix them.

**Comment by KirankumarDafda** [comment]
@zaguiini I was also looking for the same and found that adding box tag outside the window component will render the screen exact on the same size of given height and width of window.

`import { render, Window, App, Button, Box } from 'proton-native'`

`return (
      <App>
        <Window
          title="Example"
          margined
          size={{
            w: 300,
            h: this.state.height
          }}
        >
          <Box>
               <Button onClicked={this.handleResize}>
                    Change my size!
               </Button>
          </Box>
        </Window>
      </App>
    )`
