### ISSUE TITLE
Adjust prop naming conventions and defaults for easier use with JSX

### ISSUE THREAD

**Issue by j-f1** [kusti8/proton-native#82]
I’ve noticed that many if not most boolean props in this library default to `true`. For example, in [`<Box />`](https://proton-native.js.org/#/component_APIs/box), all of the props except `padded` default to `true`. This makes it more difficult to adjust their values. For example, to render a horizontal, invisible box, you need to do this:

```jsx
<Box vertical={false} visible={false} />
```

However, if the API was changed to use `false` props by default, this could be written this way instead:

```jsx
<Box hidden horizontal />
```

This saves on typing (no `={false}`) and is clearer IMO since you specify which features to enable, instead of which ones to disable.

What do you think?

**Comment by kusti8** [comment]
Seems like a good idea, but to change the name, I have to create an object mapping to translate it into libui terminology which I would rather not do since it can get really unwieldy.
