### ISSUE TITLE
Use React event naming conventions

### ISSUE THREAD

**Issue by gaearon** [kusti8/proton-native#9]
In React, events are typically called `onChange` and `onClick` rather than `onChanged` and `onClicked`. How do you feel about changing this? Great project btw!

**Comment by kusti8** [comment]
I would rather keep it closer to libui-node, since that simplifies it a lot. If you want to, you can map them, but I think it's too much work and would make the code more confusing.

**Comment by gaearon** [comment]
I see. In that case it would make sense to provide a helpful error message. Currently if you pass `onClick` it just fails somewhere in internals.

**Comment by kusti8** [comment]
Yeah one of my goals is to add error messages

**Comment by zaguini** [comment]
I don't think you should keep it closer to libui-node since you're implementing React and you know, there are a lot of conventions... Doesn't make sense to me. In the whole React world (DOM, Native, etcetera), we are used to things like `onClick`, `onPress` and so forth.

**Comment by joaoeffting** [comment]
I thougth the same when I saw onClicked :D 

But the library is so cool that I didn't mind :p

**Comment by kusti8** [comment]
Yeah I've decided that I'll do it when I get a chance.

**Comment by benwiley4000** [comment]
Here's a regex you can use to search for all the instances where this is happening:

```regex
on[A-Z][a-z]+(ed|ing)
```

* `onChanged` -> `onChange`
* `onClosing` -> `onClose`
* `onClicked` -> `onClick`
* `onToggled` -> `onToggle`
* `onSelected` -> `onSelect`
* `onContentSizeChanged` -> `onContentSizeChange`
* `onPositionChanged` -> `onPositionChange`

**Comment by kusti8** [comment]
Yeah I'm going to create a mapping for all of the callbacks, and it should
be very simple. Just an object of all the functions in DesktopComponent.js
and then change it in update and initialProps. I just need to find the time
to do it.

**Comment by kusti8** [comment]
I've decided to just replace them instead of deprecate them, because this is pretty beta, and I want to fix it quickly, and not cause more confusion

**Comment by benwiley4000** [comment]
@kusti8 Thanks for the update! It could be good to document that breaking changes can be expected. Since the package.json is past 1.0, I was assuming 1.x.x shouldn't introduce any breaking changes, and I suspect others might think the same.

**Comment by citycide** [comment]
I'm with @benwiley4000 here. Obviously the ship has sailed on doing `0.x` releases, so since you're already over 1.x this is a pretty overt semver violation. I would definitely not expect upgrading from `1.0.11` to `1.0.12` to introduce this kind of breaking change.

**Comment by kusti8** [comment]
Yeah I forgot about semvar. I won't change anything now, but i'll keep it in mind for the future.
