### ISSUE TITLE
Lists ?

### ISSUE THREAD

**Issue by jbrodriguez** [kusti8/proton-native#99]
How to render something similar to a React Native's FlatList/ListView ?

**Comment by maciek134** [comment]
@kusti8 since libui has tables now (https://godoc.org/github.com/andlabs/ui#Table) should I implement this using them, or are we waiting for some other implementation in there?

**Comment by mischnic** [comment]
You can't implement them directly in proton-native, they need to be in libui-node first (work has started in https://github.com/parro-it/libui-napi/tree/tables).

**Comment by maciek134** [comment]
Right, I meant implement it in `libui-node` and then here.

**Comment by benbucksch** [comment]
Here's how an email app without table widget with selection looks like: :-)
![image](https://user-images.githubusercontent.com/1907525/70370751-7b0b7e80-18cb-11ea-8383-2afbce5491e4.png)

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
